/*
LICENSE: BEGIN
===============================================================================
@author Shan Anand
@email anand.gs@gmail.com
@source https://github.com/shan-anand
@file constants.hpp
@brief SCSI constants, enum and macro definitions
===============================================================================
MIT License

Copyright (c) 2017 Shanmuga (Anand) Gunasekaran

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
===============================================================================
LICENSE: END
*/

/**
 * @file  constants.hpp
 * @brief Constant values in SCSI
 */

#ifndef _SID_SCSI_CONSTANTS_H_
#define _SID_SCSI_CONSTANTS_H_

#include <string>

namespace sid {
namespace block {
namespace scsi {


//! Sense keys
enum class sense_key : uint8_t
{
  no_sense            = 0x00,
  recovered_error     = 0x01,
  not_ready           = 0x02,
  medium_error        = 0x03,
  hardware_error      = 0x04,
  illegal_request     = 0x05,
  unit_attention      = 0x06,
  data_protection     = 0x07,
  blank_check         = 0x08,
  vendor_specific     = 0x09,
  copy_aborted        = 0x0a,
  command_aborted     = 0x0b,
  obsolete_0c         = 0x0c,
  volume_overflow     = 0x0d,
  miscompare          = 0x0e,
  reserved_0f         = 0x0f
};
std::string to_str(const sense_key& _e);

//! Inquiry code pages
enum class code_page : uint8_t
{
  supported_vpd_pages                 = 0x00,  //! mandatory
  unit_serial_number                  = 0x80,
  device_identification               = 0x83,  //! mandatory
  software_interface_identification   = 0x84,
  management_network_address          = 0x85,
  extended_inquiry_data               = 0x86,
  mode_page_policy                    = 0x87,
  scsi_ports                          = 0x88,
  block_limits                        = 0xb0,
  block_device_characteristics        = 0xb1,
  logical_block_provisioning          = 0xb2,
  // 0x89 to 0xaf = reserved
  // 0xb0 - 0xbf = device specific
  // 0xc0 to 0xff = vendor-specific
  custom_vpd                          = 0xff  //! custom code page. may be vendor-specific
};
std::string to_str(const code_page& _e);

//! Peripheral qualifier is a 3-bit field
enum class peripheral_qualifier : int8_t
{
  connected          = 0x00,
  disconnected       = 0x01,
  reserved_02        = 0x02,
  not_supported      = 0x03,
  vendor_specific_04 = 0x04, //! vendor-specific
  vendor_specific_05 = 0x05,
  vendor_specific_06 = 0x06,
  vendor_specific_07 = 0x07
};
std::string to_str(const peripheral_qualifier& _e);

//! Peripheral device is a 4-bit field 
enum class peripheral_device_type : int8_t
{
  direct_access            = 0x00,
  sequential_access        = 0x01,
  printer                  = 0x02,
  processor                = 0x03,
  write_once               = 0x04,
  cd_dvd                   = 0x05,
  scanner                  = 0x06,
  optical_memory           = 0x07,
  medium_changer           = 0x08,
  communications           = 0x09,
  obsolete_0a              = 0x0a,
  obsolete_0b              = 0x0b,
  storate_array_controller = 0x0c,
  enclosure_services       = 0x0d,
  simplified_direct_access = 0x0e,
  optical_card_rw          = 0x0f,
  bridge_controller        = 0x10,
  object_based_storage     = 0x11,
  automation               = 0x12,
  reserved_13              = 0x13,
  reserved_14              = 0x14,
  reserved_15              = 0x15,
  reserved_16              = 0x16,
  reserved_17              = 0x17,
  reserved_18              = 0x18,
  reserved_19              = 0x19,
  reserved_1a              = 0x1a,
  reserved_1b              = 0x1b,
  reserved_1c              = 0x1c,
  reserved_1d              = 0x1d,
  well_known_lun           = 0x1e,
  unknown                  = 0x1f
};
std::string to_str(const peripheral_device_type& _e);

enum class protocol_id : uint8_t
{
  fiber_channel = 0x00,
  parallel_scsi = 0x01,
  ssa           = 0x02,
  ieee_1394     = 0x03,
  rdma          = 0x04,
  iscsi         = 0x05,
  sas           = 0x06,
  adt           = 0x07,
  ata           = 0x08,
  reserved_9    = 0x09
};
std::string to_str(const protocol_id& _e);

enum class code_set : uint8_t
{
  binary = 0x01,
  ascii  = 0x02,
  utf8   = 0x03
};
std::string to_str(const code_set& _e);

enum class association : uint8_t
{
  logical_unit  = 0x00,
  target_port   = 0x01,
  target_device = 0x02
};
std::string to_str(const association& _e);

enum identifier_type : uint8_t
{
  vendor_specific             = 0x00,
  t10_vendor_id               = 0x01,
  eui_64                      = 0x02,
  naa                         = 0x03,
  relative_target_port        = 0x04,
  target_port_group           = 0x05,
  logical_unit_group          = 0x06,
  md5_logical_unit_id         = 0x07,
  scsi_name_string            = 0x08
};
std::string to_str(const identifier_type& _e);

enum class ascq : uint16_t
{
  no_additional_sense_information                                  = 0x0000,
  filemark_detected                                                = 0x0001,
  end_of_partition_medium_detected                                 = 0x0002,
  setmark_detected                                                 = 0x0003,
  beginning_of_partition_medium_detected                           = 0x0004,
  end_of_data_detected                                             = 0x0005,
  io_process_terminated                                            = 0x0006,
  programmable_early_warning_detected                              = 0x0007,
  audio_play_operation_in_progress                                 = 0x0011,
  audio_play_operation_paused                                      = 0x0012,
  audio_play_operation_successfully_completed                      = 0x0013,
  audio_play_operation_stopped_due_to_error                        = 0x0014,
  no_current_audio_status_to_return                                = 0x0015,
  operation_in_progress                                            = 0x0016,
  cleaning_requested                                               = 0x0017,
  erase_operation_in_progress                                      = 0x0018,
  locate_operation_in_progress                                     = 0x0019,
  rewind_operation_in_progress                                     = 0x001a,
  set_capacity_operation_in_progress                               = 0x001b,
  verify_operation_in_progress                                     = 0x001c,
  ata_pass_through_information_available                           = 0x001d,
  conflicting_sa_creation_request                                  = 0x001e,
  logical_unit_transitioning_to_another_power_condition            = 0x001f,
  extended_copy_information_available                              = 0x0020,
  atomic_command_aborted_due_to_aca                                = 0x0021,
  no_index_sector_signal                                           = 0x0100,
  no_seek_complete                                                 = 0x0200,
  peripheral_device_write_fault                                    = 0x0300,
  no_write_current                                                 = 0x0301,
  excessive_write_errors                                           = 0x0302,
  logical_unit_not_ready_cause_not_reportable                      = 0x0400,
  logical_unit_is_in_process_of_becoming_ready                     = 0x0401,
  logical_unit_not_ready_initializing_command_required             = 0x0402,
  logical_unit_not_ready_manual_intervention_required              = 0x0403,
  logical_unit_not_ready_format_in_progress                        = 0x0404,
  logical_unit_not_ready_rebuild_in_progress                       = 0x0405,
  logical_unit_not_ready_recalculation_in_progress                 = 0x0406,
  logical_unit_not_ready_operation_in_progress                     = 0x0407,
  logical_unit_not_ready_long_write_in_progress                    = 0x0408,
  logical_unit_not_ready_self_test_in_progress                     = 0x0409,
  logical_unit_not_accessible_asymmetric_access_state_transition   = 0x040a,
  logical_unit_not_accessible_target_port_in_standby_state         = 0x040b,
  logical_unit_not_accessible_target_port_in_unavailable_state     = 0x040c,
  logical_unit_not_ready_structure_check_required                  = 0x040d,
  logical_unit_not_ready_security_session_in_progress              = 0x040e,
  logical_unit_not_ready_auxiliary_memory_not_accessible           = 0x0410,
  logical_unit_not_ready_notify_enable_spinup_required             = 0x0411,
  logical_unit_not_ready_offline                                   = 0x0412,
  logical_unit_not_ready_sa_creation_in_progress                   = 0x0413,
  logical_unit_not_ready_space_allocation_in_progress              = 0x0414,
  logical_unit_not_ready_robotics_disabled                         = 0x0415,
  logical_unit_not_ready_configuration_required                    = 0x0416,
  logical_unit_not_ready_calibration_required                      = 0x0417,
  logical_unit_not_ready_a_door_is_open                            = 0x0418,
  logical_unit_not_ready_operating_in_sequential_mode              = 0x0419,
  logical_unit_not_ready_start_stop_unit_command_in_progress       = 0x041a,
  logical_unit_not_ready_sanitize_in_progress                      = 0x041b,
  logical_unit_not_ready_additional_power_use_not_yet_granted      = 0x041c,
  logical_unit_not_ready_configuration_in_progress                 = 0x041d,
  logical_unit_not_ready_microcode_activation_required             = 0x041e,
  logical_unit_not_ready_microcode_download_required               = 0x041f,
  logical_unit_not_ready_logical_unit_reset_required               = 0x0420,
  logical_unit_not_ready_hard_reset_required                       = 0x0421,
  logical_unit_not_ready_power_cycle_required                      = 0x0422,
  logical_unit_not_ready_affiliation_required                      = 0x0423,
  logical_unit_does_not_respond_to_selection                       = 0x0500,
  no_reference_position_found                                      = 0x0600,
  multiple_peripheral_devices_selected                             = 0x0700,
  logical_unit_communication_failure                               = 0x0800,
  logical_unit_communication_time_out                              = 0x0801,
  logical_unit_communication_parity_error                          = 0x0802,
  logical_unit_communication_crc_error_ultra_dma_32_               = 0x0803,
  unreachable_copy_target                                          = 0x0804,
  track_following_error                                            = 0x0900,
  tracking_servo_failure                                           = 0x0901,
  focus_servo_failure                                              = 0x0902,
  spindle_servo_failure                                            = 0x0903,
  head_select_fault                                                = 0x0904,
  vibration_induced_tracking_error                                 = 0x0905,
  error_log_overflow                                               = 0x0a00,
  warning                                                          = 0x0b00,
  warning_specified_temperature_exceeded                           = 0x0b01,
  warning_enclosure_degraded                                       = 0x0b02,
  warning_background_self_test_failed                              = 0x0b03,
  warning_background_pre_scan_detected_medium_error                = 0x0b04,
  warning_background_medium_scan_detected_medium_error             = 0x0b05,
  warning_non_volatile_cache_now_volatile                          = 0x0b06,
  warning_degraded_power_to_non_volatile_cache                     = 0x0b07,
  warning_power_loss_expected                                      = 0x0b08,
  warning_device_statistics_notification_active                    = 0x0b09,
  warning_high_critical_temperature_limit_exceeded                 = 0x0b0a,
  warning_low_critical_temperature_limit_exceeded                  = 0x0b0b,
  warning_high_operating_temperature_limit_exceeded                = 0x0b0c,
  warning_low_operating_temperature_limit_exceeded                 = 0x0b0d,
  warning_high_critical_humidity_limit_exceeded                    = 0x0b0e,
  warning_low_critical_humidity_limit_exceeded                     = 0x0b0f,
  warning_high_operating_humidity_limit_exceeded                   = 0x0b10,
  warning_low_operating_humidity_limit_exceeded                    = 0x0b11,
  warning_microcode_security_at_risk                               = 0x0b12,
  warning_microcode_digital_signature_validation_failure           = 0x0b13,
  write_error                                                      = 0x0c00,
  write_error_recovered_with_auto_reallocation                     = 0x0c01,
  write_error_auto_reallocation_failed                             = 0x0c02,
  write_error_recommend_reassignment                               = 0x0c03,
  compression_check_miscompare_error                               = 0x0c04,
  data_expansion_occurred_during_compression                       = 0x0c05,
  block_not_compressible                                           = 0x0c06,
  write_error_recovery_needed                                      = 0x0c07,
  write_error_recovery_failed                                      = 0x0c08,
  write_error_loss_of_streaming                                    = 0x0c09,
  write_error_padding_blocks_added                                 = 0x0c0a,
  auxiliary_memory_write_error                                     = 0x0c0b,
  write_error_unexpected_unsolicited_data                          = 0x0c0c,
  write_error_not_enough_unsolicited_data                          = 0x0c0d,
  multiple_write_errors                                            = 0x0c0e,
  defects_in_error_window                                          = 0x0c0f,
  incomplete_multiple_atomic_write_operations                      = 0x0c10,
  write_error_recovery_scan_needed                                 = 0x0c11,
  write_error_insufficient_zone_resources                          = 0x0c12,
  error_detected_by_third_party_temporary_initiator                = 0x0d00,
  third_party_device_failure                                       = 0x0d01,
  copy_target_device_not_reachable                                 = 0x0d02,
  incorrect_copy_target_device_type                                = 0x0d03,
  copy_target_device_data_underrun                                 = 0x0d04,
  copy_target_device_data_overrun                                  = 0x0d05,
  invalid_information_unit                                         = 0x0e00,
  information_unit_too_short                                       = 0x0e01,
  information_unit_too_long                                        = 0x0e02,
  invalid_field_in_command_information_unit                        = 0x0e03,
  custom_0f00                                                      = 0x0f00,
  id_crc_or_ecc_error                                              = 0x1000,
  logical_block_guard_check_failed                                 = 0x1001,
  logical_block_application_tag_check_failed                       = 0x1002,
  logical_block_reference_tag_check_failed                         = 0x1003,
  logical_block_protection_error_on_recover_buffered_data          = 0x1004,
  logical_block_protection_method_error                            = 0x1005,
  unrecovered_read_error                                           = 0x1100,
  read_retries_exhausted                                           = 0x1101,
  error_too_long_to_correct                                        = 0x1102,
  multiple_read_errors                                             = 0x1103,
  unrecovered_read_error_auto_reallocate_failed                    = 0x1104,
  l_ec_uncorrectable_error                                         = 0x1105,
  circ_unrecovered_error                                           = 0x1106,
  data_re_synchronization_error                                    = 0x1107,
  incomplete_block_read                                            = 0x1108,
  no_gap_found                                                     = 0x1109,
  miscorrected_error                                               = 0x110a,
  unrecovered_read_error_recommend_reassignment                    = 0x110b,
  unrecovered_read_error_recommend_rewrite_the_data                = 0x110c,
  de_compression_crc_error                                         = 0x110d,
  cannot_decompress_using_declared_algorithm                       = 0x110e,
  error_reading_upc_ean_number                                     = 0x110f,
  error_reading_isrc_number                                        = 0x1110,
  read_error_loss_of_streaming                                     = 0x1111,
  auxiliary_memory_read_error                                      = 0x1112,
  read_error_failed_retransmission_request                         = 0x1113,
  read_error_lba_marked_bad_by_application_client                  = 0x1114,
  write_after_sanitize_required                                    = 0x1115,
  address_mark_not_found_for_id_field                              = 0x1200,
  address_mark_not_found_for_data_field                            = 0x1300,
  recorded_entity_not_found                                        = 0x1400,
  record_not_found                                                 = 0x1401,
  filemark_or_setmark_not_found                                    = 0x1402,
  end_of_data_not_found                                            = 0x1403,
  block_sequence_error                                             = 0x1404,
  record_not_found_recommend_reassignment                          = 0x1405,
  record_not_found_data_auto_reallocated                           = 0x1406,
  locate_operation_failure                                         = 0x1407,
  random_positioning_error                                         = 0x1500,
  mechanical_positioning_error                                     = 0x1501,
  positioning_error_detected_by_read_of_medium                     = 0x1502,
  data_synchronization_mark_error                                  = 0x1600,
  data_sync_error_data_rewritten                                   = 0x1601,
  data_sync_error_recommend_rewrite                                = 0x1602,
  data_sync_error_data_auto_reallocated                            = 0x1603,
  data_sync_error_recommend_reassignment                           = 0x1604,
  recovered_data_with_no_error_correction_applied                  = 0x1700,
  recovered_data_with_retries                                      = 0x1701,
  recovered_data_with_positive_head_offset                         = 0x1702,
  recovered_data_with_negative_head_offset                         = 0x1703,
  recovered_data_with_retries_and_or_circ_applied                  = 0x1704,
  recovered_data_using_previous_sector_id                          = 0x1705,
  recovered_data_without_ecc_data_auto_reallocated                 = 0x1706,
  recovered_data_without_ecc_recommend_reassignment                = 0x1707,
  recovered_data_without_ecc_recommend_rewrite                     = 0x1708,
  recovered_data_without_ecc_data_rewritten                        = 0x1709,
  recovered_data_with_error_correction_applied                     = 0x1800,
  recovered_data_with_error_corr_and_retries_applied               = 0x1801,
  recovered_data_data_auto_reallocated                             = 0x1802,
  recovered_data_with_circ                                         = 0x1803,
  recovered_data_with_l_ec                                         = 0x1804,
  recovered_data_recommend_reassignment                            = 0x1805,
  recovered_data_recommend_rewrite                                 = 0x1806,
  recovered_data_with_ecc_data_rewritten                           = 0x1807,
  recovered_data_with_linking                                      = 0x1808,
  defect_list_error                                                = 0x1900,
  defect_list_not_available                                        = 0x1901,
  defect_list_error_in_primary_list                                = 0x1902,
  defect_list_error_in_grown_list                                  = 0x1903,
  parameter_list_length_error                                      = 0x1a00,
  synchronous_data_transfer_error                                  = 0x1b00,
  defect_list_not_found                                            = 0x1c00,
  primary_defect_list_not_found                                    = 0x1c01,
  grown_defect_list_not_found                                      = 0x1c02,
  miscompare_during_verify_operation                               = 0x1d00,
  miscompare_verify_of_unmapped_lba                                = 0x1d01,
  recovered_id_with_ecc_correction                                 = 0x1e00,
  partial_defect_list_transfer                                     = 0x1f00,
  invalid_command_operation_code                                   = 0x2000,
  access_denied_initiator_pending_enrolled                         = 0x2001,
  access_denied_no_access_rights                                   = 0x2002,
  access_denied_invalid_mgmt_id_key                                = 0x2003,
  illegal_command_while_in_write_capable_state                     = 0x2004,
  obsolete_2005                                                    = 0x2005,
  illegal_command_while_in_explicit_address_mode                   = 0x2006,
  illegal_command_while_in_implicit_address_mode                   = 0x2007,
  access_denied_enrollment_conflict                                = 0x2008,
  access_denied_invalid_lu_identifier                              = 0x2009,
  access_denied_invalid_proxy_token                                = 0x200a,
  access_denied_acl_lun_conflict                                   = 0x200b,
  illegal_command_when_not_in_append_only_mode                     = 0x200c,
  not_an_administrative_logical_unit                               = 0x200d,
  not_a_subsidiary_logical_unit                                    = 0x200e,
  not_a_conglomerate_logical_unit                                  = 0x200f,
  logical_block_address_out_of_range                               = 0x2100,
  invalid_element_address                                          = 0x2101,
  invalid_address_for_write                                        = 0x2102,
  invalid_write_crossing_layer_jump                                = 0x2103,
  unaligned_write_command                                          = 0x2104,
  write_boundary_violation                                         = 0x2105,
  attempt_to_read_invalid_data                                     = 0x2106,
  read_boundary_violation                                          = 0x2107,
  misaligned_write_command                                         = 0x2108,
  illegal_function_use_20_00_24_00_or_26_00_                       = 0x2200,
  invalid_token_operation_cause_not_reportable                     = 0x2300,
  invalid_token_operation_unsupported_token_type                   = 0x2301,
  invalid_token_operation_remote_token_usage_not_supported         = 0x2302,
  invalid_token_operation_remote_rod_token_creation_not_supported  = 0x2303,
  invalid_token_operation_token_unknown                            = 0x2304,
  invalid_token_operation_token_corrupt                            = 0x2305,
  invalid_token_operation_token_revoked                            = 0x2306,
  invalid_token_operation_token_expired                            = 0x2307,
  invalid_token_operation_token_cancelled                          = 0x2308,
  invalid_token_operation_token_deleted                            = 0x2309,
  invalid_token_operation_invalid_token_length                     = 0x230a,
  invalid_field_in_cdb                                             = 0x2400,
  cdb_decryption_error                                             = 0x2401,
  obsolete_2402                                                    = 0x2402,
  obsolete_2403                                                    = 0x2403,
  security_audit_value_frozen                                      = 0x2404,
  security_working_key_frozen                                      = 0x2405,
  nonce_not_unique                                                 = 0x2406,
  nonce_timestamp_out_of_range                                     = 0x2407,
  invalid_xcdb                                                     = 0x2408,
  invalid_fast_format                                              = 0x2409,
  logical_unit_not_supported                                       = 0x2500,
  invalid_field_in_parameter_list                                  = 0x2600,
  parameter_not_supported                                          = 0x2601,
  parameter_value_invalid                                          = 0x2602,
  threshold_parameters_not_supported                               = 0x2603,
  invalid_release_of_persistent_reservation                        = 0x2604,
  data_decryption_error                                            = 0x2605,
  too_many_target_descriptors                                      = 0x2606,
  unsupported_target_descriptor_type_code                          = 0x2607,
  too_many_segment_descriptors                                     = 0x2608,
  unsupported_segment_descriptor_type_code                         = 0x2609,
  unexpected_inexact_segment                                       = 0x260a,
  inline_data_length_exceeded                                      = 0x260b,
  invalid_operation_for_copy_source_or_destination                 = 0x260c,
  copy_segment_granularity_violation                               = 0x260d,
  invalid_parameter_while_port_is_enabled                          = 0x260e,
  invalid_data_out_buffer_integrity_check_value                    = 0x260f,
  data_decryption_key_fail_limit_reached                           = 0x2610,
  incomplete_key_associated_data_set                               = 0x2611,
  vendor_specific_key_reference_not_found                          = 0x2612,
  application_tag_mode_page_is_invalid                             = 0x2613,
  tape_stream_mirroring_prevented                                  = 0x2614,
  copy_source_or_copy_destination_not_authorized                   = 0x2615,
  write_protected                                                  = 0x2700,
  hardware_write_protected                                         = 0x2701,
  logical_unit_software_write_protected                            = 0x2702,
  associated_write_protect                                         = 0x2703,
  persistent_write_protect                                         = 0x2704,
  permanent_write_protect                                          = 0x2705,
  conditional_write_protect                                        = 0x2706,
  space_allocation_failed_write_protect                            = 0x2707,
  zone_is_read_only                                                = 0x2708,
  not_ready_to_ready_change_medium_may_have_changed                = 0x2800,
  import_or_export_element_accessed                                = 0x2801,
  format_layer_may_have_changed                                    = 0x2802,
  import_export_element_accessed_medium_changed                    = 0x2803,
  power_on_reset_or_bus_device_reset_occurred                      = 0x2900,
  power_on_occurred                                                = 0x2901,
  scsi_bus_reset_occurred                                          = 0x2902,
  bus_device_reset_function_occurred                               = 0x2903,
  device_internal_reset                                            = 0x2904,
  transceiver_mode_changed_to_single_ended                         = 0x2905,
  transceiver_mode_changed_to_lvd                                  = 0x2906,
  i_t_nexus_loss_occurred                                          = 0x2907,
  parameters_changed                                               = 0x2a00,
  mode_parameters_changed                                          = 0x2a01,
  log_parameters_changed                                           = 0x2a02,
  reservations_preempted                                           = 0x2a03,
  reservations_released                                            = 0x2a04,
  registrations_preempted                                          = 0x2a05,
  asymmetric_access_state_changed                                  = 0x2a06,
  implicit_asymmetric_access_state_transition_failed               = 0x2a07,
  priority_changed                                                 = 0x2a08,
  capacity_data_has_changed                                        = 0x2a09,
  error_history_i_t_nexus_cleared                                  = 0x2a0a,
  error_history_snapshot_released                                  = 0x2a0b,
  error_recovery_attributes_have_changed                           = 0x2a0c,
  data_encryption_capabilities_changed                             = 0x2a0d,
  timestamp_changed                                                = 0x2a10,
  data_encryption_parameters_changed_by_another_i_t_nexus          = 0x2a11,
  data_encryption_parameters_changed_by_vendor_specific_event      = 0x2a12,
  data_encryption_key_instance_counter_has_changed                 = 0x2a13,
  sa_creation_capabilities_data_has_changed                        = 0x2a14,
  medium_removal_prevention_preempted                              = 0x2a15,
  zone_reset_write_pointer_recommended                             = 0x2a16,
  copy_cannot_execute_since_host_cannot_disconnect                 = 0x2b00,
  command_sequence_error                                           = 0x2c00,
  too_many_windows_specified                                       = 0x2c01,
  invalid_combination_of_windows_specified                         = 0x2c02,
  current_program_area_is_not_empty                                = 0x2c03,
  current_program_area_is_empty                                    = 0x2c04,
  illegal_power_condition_request                                  = 0x2c05,
  persistent_prevent_conflict                                      = 0x2c06,
  previous_busy_status                                             = 0x2c07,
  previous_task_set_full_status                                    = 0x2c08,
  previous_reservation_conflict_status                             = 0x2c09,
  partition_or_collection_contains_user_objects                    = 0x2c0a,
  not_reserved                                                     = 0x2c0b,
  orwrite_generation_does_not_match                                = 0x2c0c,
  reset_write_pointer_not_allowed                                  = 0x2c0d,
  zone_is_offline                                                  = 0x2c0e,
  stream_not_open                                                  = 0x2c0f,
  unwritten_data_in_zone                                           = 0x2c10,
  descriptor_format_sense_data_required                            = 0x2c11,
  overwrite_error_on_update_in_place                               = 0x2d00,
  insufficient_time_for_operation                                  = 0x2e00,
  command_timeout_before_processing                                = 0x2e01,
  command_timeout_during_processing                                = 0x2e02,
  command_timeout_during_processing_due_to_error_recovery          = 0x2e03,
  commands_cleared_by_another_initiator                            = 0x2f00,
  commands_cleared_by_power_loss_notification                      = 0x2f01,
  commands_cleared_by_device_server                                = 0x2f02,
  some_commands_cleared_by_queuing_layer_event                     = 0x2f03,
  incompatible_medium_installed                                    = 0x3000,
  cannot_read_medium_unknown_format                                = 0x3001,
  cannot_read_medium_incompatible_format                           = 0x3002,
  cleaning_cartridge_installed                                     = 0x3003,
  cannot_write_medium_unknown_format                               = 0x3004,
  cannot_write_medium_incompatible_format                          = 0x3005,
  cannot_format_medium_incompatible_medium                         = 0x3006,
  cleaning_failure                                                 = 0x3007,
  cannot_write_application_code_mismatch                           = 0x3008,
  current_session_not_fixated_for_append                           = 0x3009,
  cleaning_request_rejected                                        = 0x300a,
  worm_medium_overwrite_attempted                                  = 0x300c,
  worm_medium_integrity_check                                      = 0x300d,
  medium_not_formatted                                             = 0x3010,
  incompatible_volume_type                                         = 0x3011,
  incompatible_volume_qualifier                                    = 0x3012,
  cleaning_volume_expired                                          = 0x3013,
  medium_format_corrupted                                          = 0x3100,
  format_command_failed                                            = 0x3101,
  zoned_formatting_failed_due_to_spare_linking                     = 0x3102,
  sanitize_command_failed                                          = 0x3103,
  no_defect_spare_location_available                               = 0x3200,
  defect_list_update_failure                                       = 0x3201,
  tape_length_error                                                = 0x3300,
  enclosure_failure                                                = 0x3400,
  enclosure_services_failure                                       = 0x3500,
  unsupported_enclosure_function                                   = 0x3501,
  enclosure_services_unavailable                                   = 0x3502,
  enclosure_services_transfer_failure                              = 0x3503,
  enclosure_services_transfer_refused                              = 0x3504,
  enclosure_services_checksum_error                                = 0x3505,
  ribbon_ink_or_toner_failure                                      = 0x3600,
  rounded_parameter                                                = 0x3700,
  event_status_notification                                        = 0x3800,
  esn_power_management_class_event                                 = 0x3802,
  esn_media_class_event                                            = 0x3804,
  esn_device_busy_class_event                                      = 0x3806,
  thin_provisioning_soft_threshold_reached                         = 0x3807,
  saving_parameters_not_supported                                  = 0x3900,
  medium_not_present                                               = 0x3a00,
  medium_not_present_tray_closed                                   = 0x3a01,
  medium_not_present_tray_open                                     = 0x3a02,
  medium_not_present_loadable                                      = 0x3a03,
  medium_not_present_medium_auxiliary_memory_accessible            = 0x3a04,
  sequential_positioning_error                                     = 0x3b00,
  tape_position_error_at_beginning_of_medium                       = 0x3b01,
  tape_position_error_at_end_of_medium                             = 0x3b02,
  tape_or_electronic_vertical_forms_unit_not_ready                 = 0x3b03,
  slew_failure                                                     = 0x3b04,
  paper_jam                                                        = 0x3b05,
  failed_to_sense_top_of_form                                      = 0x3b06,
  failed_to_sense_bottom_of_form                                   = 0x3b07,
  reposition_error                                                 = 0x3b08,
  read_past_end_of_medium                                          = 0x3b09,
  read_past_beginning_of_medium                                    = 0x3b0a,
  position_past_end_of_medium                                      = 0x3b0b,
  position_past_beginning_of_medium                                = 0x3b0c,
  medium_destination_element_full                                  = 0x3b0d,
  medium_source_element_empty                                      = 0x3b0e,
  end_of_medium_reached                                            = 0x3b0f,
  medium_magazine_not_accessible                                   = 0x3b11,
  medium_magazine_removed                                          = 0x3b12,
  medium_magazine_inserted                                         = 0x3b13,
  medium_magazine_locked                                           = 0x3b14,
  medium_magazine_unlocked                                         = 0x3b15,
  mechanical_positioning_or_changer_error                          = 0x3b16,
  read_past_end_of_user_object                                     = 0x3b17,
  element_disabled                                                 = 0x3b18,
  element_enabled                                                  = 0x3b19,
  data_transfer_device_removed                                     = 0x3b1a,
  data_transfer_device_inserted                                    = 0x3b1b,
  too_many_logical_objects_on_partition_to_support_operation       = 0x3b1c,
  custom_3c00                                                      = 0x3c00,
  invalid_bits_in_identify_message                                 = 0x3d00,
  logical_unit_has_not_self_configured_yet                         = 0x3e00,
  logical_unit_failure                                             = 0x3e01,
  timeout_on_logical_unit                                          = 0x3e02,
  logical_unit_failed_self_test                                    = 0x3e03,
  logical_unit_unable_to_update_self_test_log                      = 0x3e04,
  target_operating_conditions_have_changed                         = 0x3f00,
  microcode_has_been_changed                                       = 0x3f01,
  changed_operating_definition                                     = 0x3f02,
  inquiry_data_has_changed                                         = 0x3f03,
  component_device_attached                                        = 0x3f04,
  device_identifier_changed                                        = 0x3f05,
  redundancy_group_created_or_modified                             = 0x3f06,
  redundancy_group_deleted                                         = 0x3f07,
  spare_created_or_modified                                        = 0x3f08,
  spare_deleted                                                    = 0x3f09,
  volume_set_created_or_modified                                   = 0x3f0a,
  volume_set_deleted                                               = 0x3f0b,
  volume_set_deassigned                                            = 0x3f0c,
  volume_set_reassigned                                            = 0x3f0d,
  reported_luns_data_has_changed                                   = 0x3f0e,
  echo_buffer_overwritten                                          = 0x3f0f,
  medium_loadable                                                  = 0x3f10,
  medium_auxiliary_memory_accessible                               = 0x3f11,
  iscsi_ip_address_added                                           = 0x3f12,
  iscsi_ip_address_removed                                         = 0x3f13,
  iscsi_ip_address_changed                                         = 0x3f14,
  inspect_referrals_sense_descriptors                              = 0x3f15,
  microcode_has_been_changed_without_reset                         = 0x3f16,
  zone_transition_to_full                                          = 0x3f17,
  bind_completed                                                   = 0x3f18,
  bind_redirected                                                  = 0x3f19,
  subsidiary_binding_changed                                       = 0x3f1a,
  ram_failure_should_use_40_nn                                     = 0x4000,
  data_path_failure_should_use_40_nn                               = 0x4100,
  power_on_or_self_test_failure_should_use_40_nn                   = 0x4200,
  message_error                                                    = 0x4300,
  internal_target_failure                                          = 0x4400,
  persistent_reservation_information_lost                          = 0x4401,
  ata_device_failed_set_features                                   = 0x4471,
  select_or_reselect_failure                                       = 0x4500,
  unsuccessful_soft_reset                                          = 0x4600,
  scsi_parity_error                                                = 0x4700,
  data_phase_crc_error_detected                                    = 0x4701,
  scsi_parity_error_detected_during_st_data_phase                  = 0x4702,
  information_unit_iucrc_error_detected                            = 0x4703,
  asynchronous_information_protection_error_detected               = 0x4704,
  protocol_service_crc_error                                       = 0x4705,
  phy_test_function_in_progress                                    = 0x4706,
  some_commands_cleared_by_iscsi_protocol_event                    = 0x477f,
  initiator_detected_error_message_received                        = 0x4800,
  invalid_message_error                                            = 0x4900,
  command_phase_error                                              = 0x4a00,
  data_phase_error                                                 = 0x4b00,
  invalid_target_port_transfer_tag_received                        = 0x4b01,
  too_much_write_data                                              = 0x4b02,
  ack_nak_timeout                                                  = 0x4b03,
  nak_received                                                     = 0x4b04,
  data_offset_error                                                = 0x4b05,
  initiator_response_timeout                                       = 0x4b06,
  connection_lost                                                  = 0x4b07,
  data_in_buffer_overflow_data_buffer_size                         = 0x4b08,
  data_in_buffer_overflow_data_buffer_descriptor_area              = 0x4b09,
  data_in_buffer_error                                             = 0x4b0a,
  data_out_buffer_overflow_data_buffer_size                        = 0x4b0b,
  data_out_buffer_overflow_data_buffer_descriptor_area             = 0x4b0c,
  data_out_buffer_error                                            = 0x4b0d,
  pcie_fabric_error                                                = 0x4b0e,
  pcie_completion_timeout                                          = 0x4b0f,
  pcie_completer_abort                                             = 0x4b10,
  pcie_poisoned_tlp_received                                       = 0x4b11,
  pcie_ecrc_check_failed                                           = 0x4b12,
  pcie_unsupported_request                                         = 0x4b13,
  pcie_acs_violation                                               = 0x4b14,
  pcie_tlp_prefix_blocked                                          = 0x4b15,
  logical_unit_failed_self_configuration                           = 0x4c00,
  overlapped_commands_attempted                                    = 0x4e00,
  custom_4f00                                                      = 0x4f00,
  write_append_error                                               = 0x5000,
  write_append_position_error                                      = 0x5001,
  position_error_related_to_timing                                 = 0x5002,
  erase_failure                                                    = 0x5100,
  erase_failure_incomplete_erase_operation_detected                = 0x5101,
  cartridge_fault                                                  = 0x5200,
  media_load_or_eject_failed                                       = 0x5300,
  unload_tape_failure                                              = 0x5301,
  medium_removal_prevented                                         = 0x5302,
  medium_removal_prevented_by_data_transfer_element                = 0x5303,
  medium_thread_or_unthread_failure                                = 0x5304,
  volume_identifier_invalid                                        = 0x5305,
  volume_identifier_missing                                        = 0x5306,
  duplicate_volume_identifier                                      = 0x5307,
  element_status_unknown                                           = 0x5308,
  data_transfer_device_error_load_failed                           = 0x5309,
  data_transfer_device_error_unload_failed                         = 0x530a,
  data_transfer_device_error_unload_missing                        = 0x530b,
  data_transfer_device_error_eject_failed                          = 0x530c,
  data_transfer_device_error_library_communication_failed          = 0x530d,
  scsi_to_host_system_interface_failure                            = 0x5400,
  system_resource_failure                                          = 0x5500,
  system_buffer_full                                               = 0x5501,
  insufficient_reservation_resources                               = 0x5502,
  insufficient_resources                                           = 0x5503,
  insufficient_registration_resources                              = 0x5504,
  insufficient_access_control_resources                            = 0x5505,
  auxiliary_memory_out_of_space                                    = 0x5506,
  quota_error                                                      = 0x5507,
  maximum_number_of_supplemental_decryption_keys_exceeded          = 0x5508,
  medium_auxiliary_memory_not_accessible                           = 0x5509,
  data_currently_unavailable                                       = 0x550a,
  insufficient_power_for_operation                                 = 0x550b,
  insufficient_resources_to_create_rod                             = 0x550c,
  insufficient_resources_to_create_rod_token                       = 0x550d,
  insufficient_zone_resources                                      = 0x550e,
  insufficient_zone_resources_to_complete_write                    = 0x550f,
  maximum_number_of_streams_open                                   = 0x5510,
  insufficient_resources_to_bind                                   = 0x5511,
  custom_5600                                                      = 0x5600,
  unable_to_recover_table_of_contents                              = 0x5700,
  generation_does_not_exist                                        = 0x5800,
  updated_block_read                                               = 0x5900,
  operator_request_or_state_change_input                           = 0x5a00,
  operator_medium_removal_request                                  = 0x5a01,
  operator_selected_write_protect                                  = 0x5a02,
  operator_selected_write_permit                                   = 0x5a03,
  log_exception                                                    = 0x5b00,
  threshold_condition_met                                          = 0x5b01,
  log_counter_at_maximum                                           = 0x5b02,
  log_list_codes_exhausted                                         = 0x5b03,
  rpl_status_change                                                = 0x5c00,
  spindles_synchronized                                            = 0x5c01,
  spindles_not_synchronized                                        = 0x5c02,
  failure_prediction_threshold_exceeded                            = 0x5d00,
  media_failure_prediction_threshold_exceeded                      = 0x5d01,
  logical_unit_failure_prediction_threshold_exceeded               = 0x5d02,
  spare_area_exhaustion_prediction_threshold_exceeded              = 0x5d03,
  hardware_impending_failure_general_hard_drive_failure            = 0x5d10,
  hardware_impending_failure_drive_error_rate_too_high             = 0x5d11,
  hardware_impending_failure_data_error_rate_too_high              = 0x5d12,
  hardware_impending_failure_seek_error_rate_too_high              = 0x5d13,
  hardware_impending_failure_too_many_block_reassigns              = 0x5d14,
  hardware_impending_failure_access_times_too_high                 = 0x5d15,
  hardware_impending_failure_start_unit_times_too_high             = 0x5d16,
  hardware_impending_failure_channel_parametrics                   = 0x5d17,
  hardware_impending_failure_controller_detected                   = 0x5d18,
  hardware_impending_failure_throughput_performance                = 0x5d19,
  hardware_impending_failure_seek_time_performance                 = 0x5d1a,
  hardware_impending_failure_spin_up_retry_count                   = 0x5d1b,
  hardware_impending_failure_drive_calibration_retry_count         = 0x5d1c,
  hardware_impending_failure_power_loss_protection_circuit         = 0x5d1d,
  controller_impending_failure_general_hard_drive_failure          = 0x5d20,
  controller_impending_failure_drive_error_rate_too_high           = 0x5d21,
  controller_impending_failure_data_error_rate_too_high            = 0x5d22,
  controller_impending_failure_seek_error_rate_too_high            = 0x5d23,
  controller_impending_failure_too_many_block_reassigns            = 0x5d24,
  controller_impending_failure_access_times_too_high               = 0x5d25,
  controller_impending_failure_start_unit_times_too_high           = 0x5d26,
  controller_impending_failure_channel_parametrics                 = 0x5d27,
  controller_impending_failure_controller_detected                 = 0x5d28,
  controller_impending_failure_throughput_performance              = 0x5d29,
  controller_impending_failure_seek_time_performance               = 0x5d2a,
  controller_impending_failure_spin_up_retry_count                 = 0x5d2b,
  controller_impending_failure_drive_calibration_retry_count       = 0x5d2c,
  data_channel_impending_failure_general_hard_drive_failure        = 0x5d30,
  data_channel_impending_failure_drive_error_rate_too_high         = 0x5d31,
  data_channel_impending_failure_data_error_rate_too_high          = 0x5d32,
  data_channel_impending_failure_seek_error_rate_too_high          = 0x5d33,
  data_channel_impending_failure_too_many_block_reassigns          = 0x5d34,
  data_channel_impending_failure_access_times_too_high             = 0x5d35,
  data_channel_impending_failure_start_unit_times_too_high         = 0x5d36,
  data_channel_impending_failure_channel_parametrics               = 0x5d37,
  data_channel_impending_failure_controller_detected               = 0x5d38,
  data_channel_impending_failure_throughput_performance            = 0x5d39,
  data_channel_impending_failure_seek_time_performance             = 0x5d3a,
  data_channel_impending_failure_spin_up_retry_count               = 0x5d3b,
  data_channel_impending_failure_drive_calibration_retry_count     = 0x5d3c,
  servo_impending_failure_general_hard_drive_failure               = 0x5d40,
  servo_impending_failure_drive_error_rate_too_high                = 0x5d41,
  servo_impending_failure_data_error_rate_too_high                 = 0x5d42,
  servo_impending_failure_seek_error_rate_too_high                 = 0x5d43,
  servo_impending_failure_too_many_block_reassigns                 = 0x5d44,
  servo_impending_failure_access_times_too_high                    = 0x5d45,
  servo_impending_failure_start_unit_times_too_high                = 0x5d46,
  servo_impending_failure_channel_parametrics                      = 0x5d47,
  servo_impending_failure_controller_detected                      = 0x5d48,
  servo_impending_failure_throughput_performance                   = 0x5d49,
  servo_impending_failure_seek_time_performance                    = 0x5d4a,
  servo_impending_failure_spin_up_retry_count                      = 0x5d4b,
  servo_impending_failure_drive_calibration_retry_count            = 0x5d4c,
  spindle_impending_failure_general_hard_drive_failure             = 0x5d50,
  spindle_impending_failure_drive_error_rate_too_high              = 0x5d51,
  spindle_impending_failure_data_error_rate_too_high               = 0x5d52,
  spindle_impending_failure_seek_error_rate_too_high               = 0x5d53,
  spindle_impending_failure_too_many_block_reassigns               = 0x5d54,
  spindle_impending_failure_access_times_too_high                  = 0x5d55,
  spindle_impending_failure_start_unit_times_too_high              = 0x5d56,
  spindle_impending_failure_channel_parametrics                    = 0x5d57,
  spindle_impending_failure_controller_detected                    = 0x5d58,
  spindle_impending_failure_throughput_performance                 = 0x5d59,
  spindle_impending_failure_seek_time_performance                  = 0x5d5a,
  spindle_impending_failure_spin_up_retry_count                    = 0x5d5b,
  spindle_impending_failure_drive_calibration_retry_count          = 0x5d5c,
  firmware_impending_failure_general_hard_drive_failure            = 0x5d60,
  firmware_impending_failure_drive_error_rate_too_high             = 0x5d61,
  firmware_impending_failure_data_error_rate_too_high              = 0x5d62,
  firmware_impending_failure_seek_error_rate_too_high              = 0x5d63,
  firmware_impending_failure_too_many_block_reassigns              = 0x5d64,
  firmware_impending_failure_access_times_too_high                 = 0x5d65,
  firmware_impending_failure_start_unit_times_too_high             = 0x5d66,
  firmware_impending_failure_channel_parametrics                   = 0x5d67,
  firmware_impending_failure_controller_detected                   = 0x5d68,
  firmware_impending_failure_throughput_performance                = 0x5d69,
  firmware_impending_failure_seek_time_performance                 = 0x5d6a,
  firmware_impending_failure_spin_up_retry_count                   = 0x5d6b,
  firmware_impending_failure_drive_calibration_retry_count         = 0x5d6c,
  media_impending_failure_endurance_limit_met                      = 0x5d73,
  failure_prediction_threshold_exceeded_false_                     = 0x5dff,
  low_power_condition_on                                           = 0x5e00,
  idle_condition_activated_by_timer                                = 0x5e01,
  standby_condition_activated_by_timer                             = 0x5e02,
  idle_condition_activated_by_command                              = 0x5e03,
  standby_condition_activated_by_command                           = 0x5e04,
  idle_b_condition_activated_by_timer                              = 0x5e05,
  idle_b_condition_activated_by_command                            = 0x5e06,
  idle_c_condition_activated_by_timer                              = 0x5e07,
  idle_c_condition_activated_by_command                            = 0x5e08,
  standby_y_condition_activated_by_timer                           = 0x5e09,
  standby_y_condition_activated_by_command                         = 0x5e0a,
  power_state_change_to_active                                     = 0x5e41,
  power_state_change_to_idle                                       = 0x5e42,
  power_state_change_to_standby                                    = 0x5e43,
  power_state_change_to_sleep                                      = 0x5e45,
  power_state_change_to_device_control                             = 0x5e47,
  custom_5f00                                                      = 0x5f00,
  lamp_failure                                                     = 0x6000,
  video_acquisition_error                                          = 0x6100,
  unable_to_acquire_video                                          = 0x6101,
  out_of_focus                                                     = 0x6102,
  scan_head_positioning_error                                      = 0x6200,
  end_of_user_area_encountered_on_this_track                       = 0x6300,
  packet_does_not_fit_in_available_space                           = 0x6301,
  illegal_mode_for_this_track                                      = 0x6400,
  invalid_packet_size                                              = 0x6401,
  voltage_fault                                                    = 0x6500,
  automatic_document_feeder_cover_up                               = 0x6600,
  automatic_document_feeder_lift_up                                = 0x6601,
  document_jam_in_automatic_document_feeder                        = 0x6602,
  document_miss_feed_automatic_in_document_feeder                  = 0x6603,
  configuration_failure                                            = 0x6700,
  configuration_of_incapable_logical_units_failed                  = 0x6701,
  add_logical_unit_failed                                          = 0x6702,
  modification_of_logical_unit_failed                              = 0x6703,
  exchange_of_logical_unit_failed                                  = 0x6704,
  remove_of_logical_unit_failed                                    = 0x6705,
  attachment_of_logical_unit_failed                                = 0x6706,
  creation_of_logical_unit_failed                                  = 0x6707,
  assign_failure_occurred                                          = 0x6708,
  multiply_assigned_logical_unit                                   = 0x6709,
  set_target_port_groups_command_failed                            = 0x670a,
  ata_device_feature_not_enabled                                   = 0x670b,
  command_rejected                                                 = 0x670c,
  explicit_bind_not_allowed                                        = 0x670d,
  logical_unit_not_configured                                      = 0x6800,
  subsidiary_logical_unit_not_configured                           = 0x6801,
  data_loss_on_logical_unit                                        = 0x6900,
  multiple_logical_unit_failures                                   = 0x6901,
  parity_data_mismatch                                             = 0x6902,
  informational_refer_to_log                                       = 0x6a00,
  state_change_has_occurred                                        = 0x6b00,
  redundancy_level_got_better                                      = 0x6b01,
  redundancy_level_got_worse                                       = 0x6b02,
  rebuild_failure_occurred                                         = 0x6c00,
  recalculate_failure_occurred                                     = 0x6d00,
  command_to_logical_unit_failed                                   = 0x6e00,
  copy_protection_key_exchange_failure_authentication_failure      = 0x6f00,
  copy_protection_key_exchange_failure_key_not_present             = 0x6f01,
  copy_protection_key_exchange_failure_key_not_established         = 0x6f02,
  read_of_scrambled_sector_without_authentication                  = 0x6f03,
  media_region_code_is_mismatched_to_logical_unit_region           = 0x6f04,
  drive_region_must_be_permanent_region_reset_count_error          = 0x6f05,
  insufficient_block_count_for_binding_nonce_recording             = 0x6f06,
  conflict_in_binding_nonce_recording                              = 0x6f07,
  insufficient_permission                                          = 0x6f08,
  invalid_drive_host_pairing_server                                = 0x6f09,
  drive_host_pairing_suspended                                     = 0x6f0a,
  decompression_exception_long_algorithm_id                        = 0x7100,
  session_fixation_error                                           = 0x7200,
  session_fixation_error_writing_lead_in                           = 0x7201,
  session_fixation_error_writing_lead_out                          = 0x7202,
  session_fixation_error_incomplete_track_in_session               = 0x7203,
  empty_or_partially_written_reserved_track                        = 0x7204,
  no_more_track_reservations_allowed                               = 0x7205,
  rmz_extension_is_not_allowed                                     = 0x7206,
  no_more_test_zone_extensions_are_allowed                         = 0x7207,
  cd_control_error                                                 = 0x7300,
  power_calibration_area_almost_full                               = 0x7301,
  power_calibration_area_is_full                                   = 0x7302,
  power_calibration_area_error                                     = 0x7303,
  program_memory_area_update_failure                               = 0x7304,
  program_memory_area_is_full                                      = 0x7305,
  rma_pma_is_almost_full                                           = 0x7306,
  current_power_calibration_area_almost_full                       = 0x7310,
  current_power_calibration_area_is_full                           = 0x7311,
  rdz_is_full                                                      = 0x7317,
  security_error                                                   = 0x7400,
  unable_to_decrypt_data                                           = 0x7401,
  unencrypted_data_encountered_while_decrypting                    = 0x7402,
  incorrect_data_encryption_key                                    = 0x7403,
  cryptographic_integrity_validation_failed                        = 0x7404,
  error_decrypting_data                                            = 0x7405,
  unknown_signature_verification_key                               = 0x7406,
  encryption_parameters_not_useable                                = 0x7407,
  digital_signature_validation_failure                             = 0x7408,
  encryption_mode_mismatch_on_read                                 = 0x7409,
  encrypted_block_not_raw_read_enabled                             = 0x740a,
  incorrect_encryption_parameters                                  = 0x740b,
  unable_to_decrypt_parameter_list                                 = 0x740c,
  encryption_algorithm_disabled                                    = 0x740d,
  sa_creation_parameter_value_invalid                              = 0x7410,
  sa_creation_parameter_value_rejected                             = 0x7411,
  invalid_sa_usage                                                 = 0x7412,
  data_encryption_configuration_prevented                          = 0x7421,
  sa_creation_parameter_not_supported                              = 0x7430,
  authentication_failed                                            = 0x7440,
  external_data_encryption_key_manager_access_error                = 0x7461,
  external_data_encryption_key_manager_error                       = 0x7462,
  external_data_encryption_key_not_found                           = 0x7463,
  external_data_encryption_request_not_authorized                  = 0x7464,
  external_data_encryption_control_timeout                         = 0x746e,
  external_data_encryption_control_error                           = 0x746f,
  logical_unit_access_not_authorized                               = 0x7471,
  security_conflict_in_translated_device                           = 0x7479,
  custom_7500                                                      = 0x7500,
  custom_7600                                                      = 0x7600,
  custom_7700                                                      = 0x7700,
  custom_7800                                                      = 0x7800,
  custom_7900                                                      = 0x7900,
  custom_7a00                                                      = 0x7a00,
  custom_7b00                                                      = 0x7b00,
  custom_7c00                                                      = 0x7c00,
  custom_7d00                                                      = 0x7d00,
  custom_7e00                                                      = 0x7e00,
  custom_7f00                                                      = 0x7f00
};
std::string to_str(const ascq& _e);

} // namespace scsi
} // namespace block
} // namespace sid

#endif // _SID_SCSI_CONSTANTS_H_
