LIB_PROJ = sid_http
POST_SUBDIRS = client server

SOURCE_FILES = \
	common.cpp \
	cookies.cpp \
	method.cpp \
	version.cpp \
	headers.cpp \
	request.cpp \
	response.cpp \
	status.cpp \
	www_authenticate.cpp \
	url.cpp \
	connection.cpp \
	client.cpp

include $(SID_ROOT)/build.mk
