LIB_PROJ = sid_scsi

SOURCE_FILES = \
	constants.cpp \
	datatypes.cpp \
	device.cpp

include $(SID_ROOT)/build.mk
#SID_DIR=$(PWD)
#SID_FILE="build.mk"
#$(shell echo "Processing $SID_DIR"; while test ! -f $SID_DIR/$SID_FILE ; do test ($SID_DIR = "/" -o $SID_DIR = "" ) && exit -1; SID_DIR=$(dirname $SID_DIR); done;)
#include $SID_DIR/$SID_FILE
