/*
LICENSE: BEGIN
===============================================================================
@author Shanmuga (Anand) Gunasekaran
@email anand.gs@gmail.com
@source https://github.com/shan-anand
@file io_buffer.hpp
@brief SCSI constants, enum and macro definitions
===============================================================================
MIT License

Copyright (c) 2017 Shanmuga (Anand) Gunasekaran

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
===============================================================================
LICENSE: END
*/

/**
 * @file  constants.hpppppp
 * @brief Constant values in SCSI
 */

#ifndef _SID_SCSI_CONSTANTS_HPP_
#define _SID_SCSI_CONSTANTS_HPP_

#include <string>

namespace sid {
namespace scsi {

//! Verbose level, to be horored by the implementation
enum class Verbose {
  None = 0, //! No verbose
  Level_1,  //! Minimal verbose
  Level_2,  //! Medium verbose level
  Level_3,  //! Full verbose level
};

//! Sense keys
enum class SenseKey : uint8_t
{
  NO_SENSE            = 0x00,
  RECOVERED_ERROR     = 0x01,
  NOT_READY           = 0x02,
  MEDIUM_ERROR        = 0x03,
  HARDWARE_ERROR      = 0x04,
  ILLEGAL_REQUEST     = 0x05,
  UNIT_ATTENTION      = 0x06,
  DATA_PROTECTION     = 0x07,
  BLANK_CHECK         = 0x08,
  VENDOR_SPECIFIC     = 0x09,
  COPY_ABORTED        = 0x0A,
  COMMAND_ABORTED     = 0x0B,
  OBSOLETE_0C         = 0x0C,
  VOLUME_OVERFLOW     = 0x0D,
  MISCOMPARE          = 0x0E,
  RESERVED_0F         = 0x0F
};
std::string toString(const SenseKey& e);

//! Inquiry code pages
enum class CodePage : uint8_t
{
  Supported_VPD_Pages                 = 0x00,  //! Mandatory
  Unit_Serial_Number                  = 0x80,
  Device_Identification               = 0x83,  //! Mandatory
  Software_Interface_Identification   = 0x84,
  Management_Network_Address          = 0x85,
  Extended_Inquiry_Data               = 0x86,
  Mode_Page_Policy                    = 0x87,
  SCSI_Ports                          = 0x88,
  Block_Limits                        = 0xB0,
  Block_Device_Characteristics        = 0xB1,
  Logical_Block_Provisioning          = 0xB2,
  // 0x89 to 0xAF = Reserved
  // 0xB0 - 0xBF = Device specific
  // 0xC0 to 0xFF = Vendor-Specific
  Custom_VPD                          = 0xFF  //! Custom Code page. May be Vendor-specific
};
std::string toString(const CodePage& e);

//! Peripheral qualifier is a 3-bit field
enum class Peripheral_Qualifier : int8_t
{
  Connected          = 0x00,
  Disconnected       = 0x01,
  Reserved_02        = 0x02,
  Not_Supported      = 0x03,
  Vendor_Specific_04 = 0x04, //! vendor-specific
  Vendor_Specific_05 = 0x05,
  Vendor_Specific_06 = 0x06,
  Vendor_Specific_07 = 0x07
};
std::string toString(const Peripheral_Qualifier& e);

//! Peripheral device is a 4-bit field
enum class Peripheral_Device_Type : int8_t
{
  Direct_Access            = 0x00,
  Sequential_Access        = 0x01,
  Printer                  = 0x02,
  Processor                = 0x03,
  Write_Once               = 0x04,
  Cd_Dvd                   = 0x05,
  Scanner                  = 0x06,
  Optical_Memory           = 0x07,
  Medium_Changer           = 0x08,
  Communications           = 0x09,
  Obsolete_0A              = 0x0A,
  Obsolete_0B              = 0x0B,
  Storate_Array_Controller = 0x0C,
  Enclosure_Services       = 0x0D,
  Simplified_Direct_Access = 0x0E,
  Optical_Card_RW          = 0x0F,
  Bridge_Controller        = 0x10,
  Object_Based_Storage     = 0x11,
  Automation               = 0x12,
  Reserved_13              = 0x13,
  Reserved_14              = 0x14,
  Reserved_15              = 0x15,
  Reserved_16              = 0x16,
  Reserved_17              = 0x17,
  Reserved_18              = 0x18,
  Reserved_19              = 0x19,
  Reserved_1A              = 0x1A,
  Reserved_1B              = 0x1B,
  Reserved_1C              = 0x1C,
  Reserved_1D              = 0x1D,
  Well_Known_Lun           = 0x1E,
  Unknown                  = 0x1F
};
std::string toString(const Peripheral_Device_Type& e);

enum class ProtocolId : uint8_t
{
  Fiber_Channel = 0x00,
  Parallel_Scsi = 0x01,
  SSA           = 0x02,
  IEEE_1394     = 0x03,
  RDMA          = 0x04,
  IScsi         = 0x05,
  SAS           = 0x06,
  ADT           = 0x07,
  ATA           = 0x08,
  Reserved_9    = 0x09
};
std::string toString(const ProtocolId& e);

enum class CodeSet : uint8_t
{
  Binary = 0x01,
  ASCII  = 0x02,
  UTF8   = 0x03
};
std::string toString(const CodeSet& e);

enum class Association : uint8_t
{
  Logical_Unit  = 0x00,
  Target_Port   = 0x01,
  Target_Device = 0x02
};
std::string toString(const Association& e);

enum IdentifierType : uint8_t
{
  Vendor_Specific             = 0x00,
  T10_Vendor_Id               = 0x01,
  EUI_64                      = 0x02,
  NAA                         = 0x03,
  Relative_Target_Port        = 0x04,
  Target_Port_Group           = 0x05,
  Logical_Unit_Group          = 0x06,
  MD5_Logical_Unit_Id         = 0x07,
  Scsi_Name_String            = 0x08
};
std::string toString(const IdentifierType& e);

enum class ASCQ : uint16_t
{
  NO_ADDITIONAL_SENSE_INFORMATION                                  = 0x0000,
  FILEMARK_DETECTED                                                = 0x0001,
  END_OF_PARTITION_MEDIUM_DETECTED                                 = 0x0002,
  SETMARK_DETECTED                                                 = 0x0003,
  BEGINNING_OF_PARTITION_MEDIUM_DETECTED                           = 0x0004,
  END_OF_DATA_DETECTED                                             = 0x0005,
  I_O_PROCESS_TERMINATED                                           = 0x0006,
  PROGRAMMABLE_EARLY_WARNING_DETECTED                              = 0x0007,
  AUDIO_PLAY_OPERATION_IN_PROGRESS                                 = 0x0011,
  AUDIO_PLAY_OPERATION_PAUSED                                      = 0x0012,
  AUDIO_PLAY_OPERATION_SUCCESSFULLY_COMPLETED                      = 0x0013,
  AUDIO_PLAY_OPERATION_STOPPED_DUE_TO_ERROR                        = 0x0014,
  NO_CURRENT_AUDIO_STATUS_TO_RETURN                                = 0x0015,
  OPERATION_IN_PROGRESS                                            = 0x0016,
  CLEANING_REQUESTED                                               = 0x0017,
  ERASE_OPERATION_IN_PROGRESS                                      = 0x0018,
  LOCATE_OPERATION_IN_PROGRESS                                     = 0x0019,
  REWIND_OPERATION_IN_PROGRESS                                     = 0x001A,
  SET_CAPACITY_OPERATION_IN_PROGRESS                               = 0x001B,
  VERIFY_OPERATION_IN_PROGRESS                                     = 0x001C,
  ATA_PASS_THROUGH_INFORMATION_AVAILABLE                           = 0x001D,
  CONFLICTING_SA_CREATION_REQUEST                                  = 0x001E,
  LOGICAL_UNIT_TRANSITIONING_TO_ANOTHER_POWER_CONDITION            = 0x001F,
  EXTENDED_COPY_INFORMATION_AVAILABLE                              = 0x0020,
  ATOMIC_COMMAND_ABORTED_DUE_TO_ACA                                = 0x0021,
  NO_INDEX_SECTOR_SIGNAL                                           = 0x0100,
  NO_SEEK_COMPLETE                                                 = 0x0200,
  PERIPHERAL_DEVICE_WRITE_FAULT                                    = 0x0300,
  NO_WRITE_CURRENT                                                 = 0x0301,
  EXCESSIVE_WRITE_ERRORS                                           = 0x0302,
  LOGICAL_UNIT_NOT_READY_CAUSE_NOT_REPORTABLE                      = 0x0400,
  LOGICAL_UNIT_IS_IN_PROCESS_OF_BECOMING_READY                     = 0x0401,
  LOGICAL_UNIT_NOT_READY_INITIALIZING_COMMAND_REQUIRED             = 0x0402,
  LOGICAL_UNIT_NOT_READY_MANUAL_INTERVENTION_REQUIRED              = 0x0403,
  LOGICAL_UNIT_NOT_READY_FORMAT_IN_PROGRESS                        = 0x0404,
  LOGICAL_UNIT_NOT_READY_REBUILD_IN_PROGRESS                       = 0x0405,
  LOGICAL_UNIT_NOT_READY_RECALCULATION_IN_PROGRESS                 = 0x0406,
  LOGICAL_UNIT_NOT_READY_OPERATION_IN_PROGRESS                     = 0x0407,
  LOGICAL_UNIT_NOT_READY_LONG_WRITE_IN_PROGRESS                    = 0x0408,
  LOGICAL_UNIT_NOT_READY_SELF_TEST_IN_PROGRESS                     = 0x0409,
  LOGICAL_UNIT_NOT_ACCESSIBLE_ASYMMETRIC_ACCESS_STATE_TRANSITION   = 0x040A,
  LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_STANDBY_STATE         = 0x040B,
  LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_UNAVAILABLE_STATE     = 0x040C,
  LOGICAL_UNIT_NOT_READY_STRUCTURE_CHECK_REQUIRED                  = 0x040D,
  LOGICAL_UNIT_NOT_READY_SECURITY_SESSION_IN_PROGRESS              = 0x040E,
  LOGICAL_UNIT_NOT_READY_AUXILIARY_MEMORY_NOT_ACCESSIBLE           = 0x0410,
  LOGICAL_UNIT_NOT_READY_NOTIFY_ENABLE_SPINUP_REQUIRED             = 0x0411,
  LOGICAL_UNIT_NOT_READY_OFFLINE                                   = 0x0412,
  LOGICAL_UNIT_NOT_READY_SA_CREATION_IN_PROGRESS                   = 0x0413,
  LOGICAL_UNIT_NOT_READY_SPACE_ALLOCATION_IN_PROGRESS              = 0x0414,
  LOGICAL_UNIT_NOT_READY_ROBOTICS_DISABLED                         = 0x0415,
  LOGICAL_UNIT_NOT_READY_CONFIGURATION_REQUIRED                    = 0x0416,
  LOGICAL_UNIT_NOT_READY_CALIBRATION_REQUIRED                      = 0x0417,
  LOGICAL_UNIT_NOT_READY_A_DOOR_IS_OPEN                            = 0x0418,
  LOGICAL_UNIT_NOT_READY_OPERATING_IN_SEQUENTIAL_MODE              = 0x0419,
  LOGICAL_UNIT_NOT_READY_START_STOP_UNIT_COMMAND_IN_PROGRESS       = 0x041A,
  LOGICAL_UNIT_NOT_READY_SANITIZE_IN_PROGRESS                      = 0x041B,
  LOGICAL_UNIT_NOT_READY_ADDITIONAL_POWER_USE_NOT_YET_GRANTED      = 0x041C,
  LOGICAL_UNIT_NOT_READY_CONFIGURATION_IN_PROGRESS                 = 0x041D,
  LOGICAL_UNIT_NOT_READY_MICROCODE_ACTIVATION_REQUIRED             = 0x041E,
  LOGICAL_UNIT_NOT_READY_MICROCODE_DOWNLOAD_REQUIRED               = 0x041F,
  LOGICAL_UNIT_NOT_READY_LOGICAL_UNIT_RESET_REQUIRED               = 0x0420,
  LOGICAL_UNIT_NOT_READY_HARD_RESET_REQUIRED                       = 0x0421,
  LOGICAL_UNIT_NOT_READY_POWER_CYCLE_REQUIRED                      = 0x0422,
  LOGICAL_UNIT_NOT_READY_AFFILIATION_REQUIRED                      = 0x0423,
  LOGICAL_UNIT_DOES_NOT_RESPOND_TO_SELECTION                       = 0x0500,
  NO_REFERENCE_POSITION_FOUND                                      = 0x0600,
  MULTIPLE_PERIPHERAL_DEVICES_SELECTED                             = 0x0700,
  LOGICAL_UNIT_COMMUNICATION_FAILURE                               = 0x0800,
  LOGICAL_UNIT_COMMUNICATION_TIME_OUT                              = 0x0801,
  LOGICAL_UNIT_COMMUNICATION_PARITY_ERROR                          = 0x0802,
  LOGICAL_UNIT_COMMUNICATION_CRC_ERROR_ULTRA_DMA_32_               = 0x0803,
  UNREACHABLE_COPY_TARGET                                          = 0x0804,
  TRACK_FOLLOWING_ERROR                                            = 0x0900,
  TRACKING_SERVO_FAILURE                                           = 0x0901,
  FOCUS_SERVO_FAILURE                                              = 0x0902,
  SPINDLE_SERVO_FAILURE                                            = 0x0903,
  HEAD_SELECT_FAULT                                                = 0x0904,
  VIBRATION_INDUCED_TRACKING_ERROR                                 = 0x0905,
  ERROR_LOG_OVERFLOW                                               = 0x0A00,
  WARNING                                                          = 0x0B00,
  WARNING_SPECIFIED_TEMPERATURE_EXCEEDED                           = 0x0B01,
  WARNING_ENCLOSURE_DEGRADED                                       = 0x0B02,
  WARNING_BACKGROUND_SELF_TEST_FAILED                              = 0x0B03,
  WARNING_BACKGROUND_PRE_SCAN_DETECTED_MEDIUM_ERROR                = 0x0B04,
  WARNING_BACKGROUND_MEDIUM_SCAN_DETECTED_MEDIUM_ERROR             = 0x0B05,
  WARNING_NON_VOLATILE_CACHE_NOW_VOLATILE                          = 0x0B06,
  WARNING_DEGRADED_POWER_TO_NON_VOLATILE_CACHE                     = 0x0B07,
  WARNING_POWER_LOSS_EXPECTED                                      = 0x0B08,
  WARNING_DEVICE_STATISTICS_NOTIFICATION_ACTIVE                    = 0x0B09,
  WARNING_HIGH_CRITICAL_TEMPERATURE_LIMIT_EXCEEDED                 = 0x0B0A,
  WARNING_LOW_CRITICAL_TEMPERATURE_LIMIT_EXCEEDED                  = 0x0B0B,
  WARNING_HIGH_OPERATING_TEMPERATURE_LIMIT_EXCEEDED                = 0x0B0C,
  WARNING_LOW_OPERATING_TEMPERATURE_LIMIT_EXCEEDED                 = 0x0B0D,
  WARNING_HIGH_CRITICAL_HUMIDITY_LIMIT_EXCEEDED                    = 0x0B0E,
  WARNING_LOW_CRITICAL_HUMIDITY_LIMIT_EXCEEDED                     = 0x0B0F,
  WARNING_HIGH_OPERATING_HUMIDITY_LIMIT_EXCEEDED                   = 0x0B10,
  WARNING_LOW_OPERATING_HUMIDITY_LIMIT_EXCEEDED                    = 0x0B11,
  WARNING_MICROCODE_SECURITY_AT_RISK                               = 0x0B12,
  WARNING_MICROCODE_DIGITAL_SIGNATURE_VALIDATION_FAILURE           = 0x0B13,
  WRITE_ERROR                                                      = 0x0C00,
  WRITE_ERROR_RECOVERED_WITH_AUTO_REALLOCATION                     = 0x0C01,
  WRITE_ERROR_AUTO_REALLOCATION_FAILED                             = 0x0C02,
  WRITE_ERROR_RECOMMEND_REASSIGNMENT                               = 0x0C03,
  COMPRESSION_CHECK_MISCOMPARE_ERROR                               = 0x0C04,
  DATA_EXPANSION_OCCURRED_DURING_COMPRESSION                       = 0x0C05,
  BLOCK_NOT_COMPRESSIBLE                                           = 0x0C06,
  WRITE_ERROR_RECOVERY_NEEDED                                      = 0x0C07,
  WRITE_ERROR_RECOVERY_FAILED                                      = 0x0C08,
  WRITE_ERROR_LOSS_OF_STREAMING                                    = 0x0C09,
  WRITE_ERROR_PADDING_BLOCKS_ADDED                                 = 0x0C0A,
  AUXILIARY_MEMORY_WRITE_ERROR                                     = 0x0C0B,
  WRITE_ERROR_UNEXPECTED_UNSOLICITED_DATA                          = 0x0C0C,
  WRITE_ERROR_NOT_ENOUGH_UNSOLICITED_DATA                          = 0x0C0D,
  MULTIPLE_WRITE_ERRORS                                            = 0x0C0E,
  DEFECTS_IN_ERROR_WINDOW                                          = 0x0C0F,
  INCOMPLETE_MULTIPLE_ATOMIC_WRITE_OPERATIONS                      = 0x0C10,
  WRITE_ERROR_RECOVERY_SCAN_NEEDED                                 = 0x0C11,
  WRITE_ERROR_INSUFFICIENT_ZONE_RESOURCES                          = 0x0C12,
  ERROR_DETECTED_BY_THIRD_PARTY_TEMPORARY_INITIATOR                = 0x0D00,
  THIRD_PARTY_DEVICE_FAILURE                                       = 0x0D01,
  COPY_TARGET_DEVICE_NOT_REACHABLE                                 = 0x0D02,
  INCORRECT_COPY_TARGET_DEVICE_TYPE                                = 0x0D03,
  COPY_TARGET_DEVICE_DATA_UNDERRUN                                 = 0x0D04,
  COPY_TARGET_DEVICE_DATA_OVERRUN                                  = 0x0D05,
  INVALID_INFORMATION_UNIT                                         = 0x0E00,
  INFORMATION_UNIT_TOO_SHORT                                       = 0x0E01,
  INFORMATION_UNIT_TOO_LONG                                        = 0x0E02,
  INVALID_FIELD_IN_COMMAND_INFORMATION_UNIT                        = 0x0E03,
  CUSTOM_0F00                                                      = 0x0F00,
  ID_CRC_OR_ECC_ERROR                                              = 0x1000,
  LOGICAL_BLOCK_GUARD_CHECK_FAILED                                 = 0x1001,
  LOGICAL_BLOCK_APPLICATION_TAG_CHECK_FAILED                       = 0x1002,
  LOGICAL_BLOCK_REFERENCE_TAG_CHECK_FAILED                         = 0x1003,
  LOGICAL_BLOCK_PROTECTION_ERROR_ON_RECOVER_BUFFERED_DATA          = 0x1004,
  LOGICAL_BLOCK_PROTECTION_METHOD_ERROR                            = 0x1005,
  UNRECOVERED_READ_ERROR                                           = 0x1100,
  READ_RETRIES_EXHAUSTED                                           = 0x1101,
  ERROR_TOO_LONG_TO_CORRECT                                        = 0x1102,
  MULTIPLE_READ_ERRORS                                             = 0x1103,
  UNRECOVERED_READ_ERROR_AUTO_REALLOCATE_FAILED                    = 0x1104,
  L_EC_UNCORRECTABLE_ERROR                                         = 0x1105,
  CIRC_UNRECOVERED_ERROR                                           = 0x1106,
  DATA_RE_SYNCHRONIZATION_ERROR                                    = 0x1107,
  INCOMPLETE_BLOCK_READ                                            = 0x1108,
  NO_GAP_FOUND                                                     = 0x1109,
  MISCORRECTED_ERROR                                               = 0x110A,
  UNRECOVERED_READ_ERROR_RECOMMEND_REASSIGNMENT                    = 0x110B,
  UNRECOVERED_READ_ERROR_RECOMMEND_REWRITE_THE_DATA                = 0x110C,
  DE_COMPRESSION_CRC_ERROR                                         = 0x110D,
  CANNOT_DECOMPRESS_USING_DECLARED_ALGORITHM                       = 0x110E,
  ERROR_READING_UPC_EAN_NUMBER                                     = 0x110F,
  ERROR_READING_ISRC_NUMBER                                        = 0x1110,
  READ_ERROR_LOSS_OF_STREAMING                                     = 0x1111,
  AUXILIARY_MEMORY_READ_ERROR                                      = 0x1112,
  READ_ERROR_FAILED_RETRANSMISSION_REQUEST                         = 0x1113,
  READ_ERROR_LBA_MARKED_BAD_BY_APPLICATION_CLIENT                  = 0x1114,
  WRITE_AFTER_SANITIZE_REQUIRED                                    = 0x1115,
  ADDRESS_MARK_NOT_FOUND_FOR_ID_FIELD                              = 0x1200,
  ADDRESS_MARK_NOT_FOUND_FOR_DATA_FIELD                            = 0x1300,
  RECORDED_ENTITY_NOT_FOUND                                        = 0x1400,
  RECORD_NOT_FOUND                                                 = 0x1401,
  FILEMARK_OR_SETMARK_NOT_FOUND                                    = 0x1402,
  END_OF_DATA_NOT_FOUND                                            = 0x1403,
  BLOCK_SEQUENCE_ERROR                                             = 0x1404,
  RECORD_NOT_FOUND_RECOMMEND_REASSIGNMENT                          = 0x1405,
  RECORD_NOT_FOUND_DATA_AUTO_REALLOCATED                           = 0x1406,
  LOCATE_OPERATION_FAILURE                                         = 0x1407,
  RANDOM_POSITIONING_ERROR                                         = 0x1500,
  MECHANICAL_POSITIONING_ERROR                                     = 0x1501,
  POSITIONING_ERROR_DETECTED_BY_READ_OF_MEDIUM                     = 0x1502,
  DATA_SYNCHRONIZATION_MARK_ERROR                                  = 0x1600,
  DATA_SYNC_ERROR_DATA_REWRITTEN                                   = 0x1601,
  DATA_SYNC_ERROR_RECOMMEND_REWRITE                                = 0x1602,
  DATA_SYNC_ERROR_DATA_AUTO_REALLOCATED                            = 0x1603,
  DATA_SYNC_ERROR_RECOMMEND_REASSIGNMENT                           = 0x1604,
  RECOVERED_DATA_WITH_NO_ERROR_CORRECTION_APPLIED                  = 0x1700,
  RECOVERED_DATA_WITH_RETRIES                                      = 0x1701,
  RECOVERED_DATA_WITH_POSITIVE_HEAD_OFFSET                         = 0x1702,
  RECOVERED_DATA_WITH_NEGATIVE_HEAD_OFFSET                         = 0x1703,
  RECOVERED_DATA_WITH_RETRIES_AND_OR_CIRC_APPLIED                  = 0x1704,
  RECOVERED_DATA_USING_PREVIOUS_SECTOR_ID                          = 0x1705,
  RECOVERED_DATA_WITHOUT_ECC_DATA_AUTO_REALLOCATED                 = 0x1706,
  RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REASSIGNMENT                = 0x1707,
  RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REWRITE                     = 0x1708,
  RECOVERED_DATA_WITHOUT_ECC_DATA_REWRITTEN                        = 0x1709,
  RECOVERED_DATA_WITH_ERROR_CORRECTION_APPLIED                     = 0x1800,
  RECOVERED_DATA_WITH_ERROR_CORR_AND_RETRIES_APPLIED               = 0x1801,
  RECOVERED_DATA_DATA_AUTO_REALLOCATED                             = 0x1802,
  RECOVERED_DATA_WITH_CIRC                                         = 0x1803,
  RECOVERED_DATA_WITH_L_EC                                         = 0x1804,
  RECOVERED_DATA_RECOMMEND_REASSIGNMENT                            = 0x1805,
  RECOVERED_DATA_RECOMMEND_REWRITE                                 = 0x1806,
  RECOVERED_DATA_WITH_ECC_DATA_REWRITTEN                           = 0x1807,
  RECOVERED_DATA_WITH_LINKING                                      = 0x1808,
  DEFECT_LIST_ERROR                                                = 0x1900,
  DEFECT_LIST_NOT_AVAILABLE                                        = 0x1901,
  DEFECT_LIST_ERROR_IN_PRIMARY_LIST                                = 0x1902,
  DEFECT_LIST_ERROR_IN_GROWN_LIST                                  = 0x1903,
  PARAMETER_LIST_LENGTH_ERROR                                      = 0x1A00,
  SYNCHRONOUS_DATA_TRANSFER_ERROR                                  = 0x1B00,
  DEFECT_LIST_NOT_FOUND                                            = 0x1C00,
  PRIMARY_DEFECT_LIST_NOT_FOUND                                    = 0x1C01,
  GROWN_DEFECT_LIST_NOT_FOUND                                      = 0x1C02,
  MISCOMPARE_DURING_VERIFY_OPERATION                               = 0x1D00,
  MISCOMPARE_VERIFY_OF_UNMAPPED_LBA                                = 0x1D01,
  RECOVERED_ID_WITH_ECC_CORRECTION                                 = 0x1E00,
  PARTIAL_DEFECT_LIST_TRANSFER                                     = 0x1F00,
  INVALID_COMMAND_OPERATION_CODE                                   = 0x2000,
  ACCESS_DENIED_INITIATOR_PENDING_ENROLLED                         = 0x2001,
  ACCESS_DENIED_NO_ACCESS_RIGHTS                                   = 0x2002,
  ACCESS_DENIED_INVALID_MGMT_ID_KEY                                = 0x2003,
  ILLEGAL_COMMAND_WHILE_IN_WRITE_CAPABLE_STATE                     = 0x2004,
  OBSOLETE_2005                                                    = 0x2005,
  ILLEGAL_COMMAND_WHILE_IN_EXPLICIT_ADDRESS_MODE                   = 0x2006,
  ILLEGAL_COMMAND_WHILE_IN_IMPLICIT_ADDRESS_MODE                   = 0x2007,
  ACCESS_DENIED_ENROLLMENT_CONFLICT                                = 0x2008,
  ACCESS_DENIED_INVALID_LU_IDENTIFIER                              = 0x2009,
  ACCESS_DENIED_INVALID_PROXY_TOKEN                                = 0x200A,
  ACCESS_DENIED_ACL_LUN_CONFLICT                                   = 0x200B,
  ILLEGAL_COMMAND_WHEN_NOT_IN_APPEND_ONLY_MODE                     = 0x200C,
  NOT_AN_ADMINISTRATIVE_LOGICAL_UNIT                               = 0x200D,
  NOT_A_SUBSIDIARY_LOGICAL_UNIT                                    = 0x200E,
  NOT_A_CONGLOMERATE_LOGICAL_UNIT                                  = 0x200F,
  LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE                               = 0x2100,
  INVALID_ELEMENT_ADDRESS                                          = 0x2101,
  INVALID_ADDRESS_FOR_WRITE                                        = 0x2102,
  INVALID_WRITE_CROSSING_LAYER_JUMP                                = 0x2103,
  UNALIGNED_WRITE_COMMAND                                          = 0x2104,
  WRITE_BOUNDARY_VIOLATION                                         = 0x2105,
  ATTEMPT_TO_READ_INVALID_DATA                                     = 0x2106,
  READ_BOUNDARY_VIOLATION                                          = 0x2107,
  MISALIGNED_WRITE_COMMAND                                         = 0x2108,
  ILLEGAL_FUNCTION_USE_20_00_24_00_OR_26_00_                       = 0x2200,
  INVALID_TOKEN_OPERATION_CAUSE_NOT_REPORTABLE                     = 0x2300,
  INVALID_TOKEN_OPERATION_UNSUPPORTED_TOKEN_TYPE                   = 0x2301,
  INVALID_TOKEN_OPERATION_REMOTE_TOKEN_USAGE_NOT_SUPPORTED         = 0x2302,
  INVALID_TOKEN_OPERATION_REMOTE_ROD_TOKEN_CREATION_NOT_SUPPORTED  = 0x2303,
  INVALID_TOKEN_OPERATION_TOKEN_UNKNOWN                            = 0x2304,
  INVALID_TOKEN_OPERATION_TOKEN_CORRUPT                            = 0x2305,
  INVALID_TOKEN_OPERATION_TOKEN_REVOKED                            = 0x2306,
  INVALID_TOKEN_OPERATION_TOKEN_EXPIRED                            = 0x2307,
  INVALID_TOKEN_OPERATION_TOKEN_CANCELLED                          = 0x2308,
  INVALID_TOKEN_OPERATION_TOKEN_DELETED                            = 0x2309,
  INVALID_TOKEN_OPERATION_INVALID_TOKEN_LENGTH                     = 0x230A,
  INVALID_FIELD_IN_CDB                                             = 0x2400,
  CDB_DECRYPTION_ERROR                                             = 0x2401,
  OBSOLETE_2402                                                    = 0x2402,
  OBSOLETE_2403                                                    = 0x2403,
  SECURITY_AUDIT_VALUE_FROZEN                                      = 0x2404,
  SECURITY_WORKING_KEY_FROZEN                                      = 0x2405,
  NONCE_NOT_UNIQUE                                                 = 0x2406,
  NONCE_TIMESTAMP_OUT_OF_RANGE                                     = 0x2407,
  INVALID_XCDB                                                     = 0x2408,
  INVALID_FAST_FORMAT                                              = 0x2409,
  LOGICAL_UNIT_NOT_SUPPORTED                                       = 0x2500,
  INVALID_FIELD_IN_PARAMETER_LIST                                  = 0x2600,
  PARAMETER_NOT_SUPPORTED                                          = 0x2601,
  PARAMETER_VALUE_INVALID                                          = 0x2602,
  THRESHOLD_PARAMETERS_NOT_SUPPORTED                               = 0x2603,
  INVALID_RELEASE_OF_PERSISTENT_RESERVATION                        = 0x2604,
  DATA_DECRYPTION_ERROR                                            = 0x2605,
  TOO_MANY_TARGET_DESCRIPTORS                                      = 0x2606,
  UNSUPPORTED_TARGET_DESCRIPTOR_TYPE_CODE                          = 0x2607,
  TOO_MANY_SEGMENT_DESCRIPTORS                                     = 0x2608,
  UNSUPPORTED_SEGMENT_DESCRIPTOR_TYPE_CODE                         = 0x2609,
  UNEXPECTED_INEXACT_SEGMENT                                       = 0x260A,
  INLINE_DATA_LENGTH_EXCEEDED                                      = 0x260B,
  INVALID_OPERATION_FOR_COPY_SOURCE_OR_DESTINATION                 = 0x260C,
  COPY_SEGMENT_GRANULARITY_VIOLATION                               = 0x260D,
  INVALID_PARAMETER_WHILE_PORT_IS_ENABLED                          = 0x260E,
  INVALID_DATA_OUT_BUFFER_INTEGRITY_CHECK_VALUE                    = 0x260F,
  DATA_DECRYPTION_KEY_FAIL_LIMIT_REACHED                           = 0x2610,
  INCOMPLETE_KEY_ASSOCIATED_DATA_SET                               = 0x2611,
  VENDOR_SPECIFIC_KEY_REFERENCE_NOT_FOUND                          = 0x2612,
  APPLICATION_TAG_MODE_PAGE_IS_INVALID                             = 0x2613,
  TAPE_STREAM_MIRRORING_PREVENTED                                  = 0x2614,
  COPY_SOURCE_OR_COPY_DESTINATION_NOT_AUTHORIZED                   = 0x2615,
  WRITE_PROTECTED                                                  = 0x2700,
  HARDWARE_WRITE_PROTECTED                                         = 0x2701,
  LOGICAL_UNIT_SOFTWARE_WRITE_PROTECTED                            = 0x2702,
  ASSOCIATED_WRITE_PROTECT                                         = 0x2703,
  PERSISTENT_WRITE_PROTECT                                         = 0x2704,
  PERMANENT_WRITE_PROTECT                                          = 0x2705,
  CONDITIONAL_WRITE_PROTECT                                        = 0x2706,
  SPACE_ALLOCATION_FAILED_WRITE_PROTECT                            = 0x2707,
  ZONE_IS_READ_ONLY                                                = 0x2708,
  NOT_READY_TO_READY_CHANGE_MEDIUM_MAY_HAVE_CHANGED                = 0x2800,
  IMPORT_OR_EXPORT_ELEMENT_ACCESSED                                = 0x2801,
  FORMAT_LAYER_MAY_HAVE_CHANGED                                    = 0x2802,
  IMPORT_EXPORT_ELEMENT_ACCESSED_MEDIUM_CHANGED                    = 0x2803,
  POWER_ON_RESET_OR_BUS_DEVICE_RESET_OCCURRED                      = 0x2900,
  POWER_ON_OCCURRED                                                = 0x2901,
  SCSI_BUS_RESET_OCCURRED                                          = 0x2902,
  BUS_DEVICE_RESET_FUNCTION_OCCURRED                               = 0x2903,
  DEVICE_INTERNAL_RESET                                            = 0x2904,
  TRANSCEIVER_MODE_CHANGED_TO_SINGLE_ENDED                         = 0x2905,
  TRANSCEIVER_MODE_CHANGED_TO_LVD                                  = 0x2906,
  I_T_NEXUS_LOSS_OCCURRED                                          = 0x2907,
  PARAMETERS_CHANGED                                               = 0x2A00,
  MODE_PARAMETERS_CHANGED                                          = 0x2A01,
  LOG_PARAMETERS_CHANGED                                           = 0x2A02,
  RESERVATIONS_PREEMPTED                                           = 0x2A03,
  RESERVATIONS_RELEASED                                            = 0x2A04,
  REGISTRATIONS_PREEMPTED                                          = 0x2A05,
  ASYMMETRIC_ACCESS_STATE_CHANGED                                  = 0x2A06,
  IMPLICIT_ASYMMETRIC_ACCESS_STATE_TRANSITION_FAILED               = 0x2A07,
  PRIORITY_CHANGED                                                 = 0x2A08,
  CAPACITY_DATA_HAS_CHANGED                                        = 0x2A09,
  ERROR_HISTORY_I_T_NEXUS_CLEARED                                  = 0x2A0A,
  ERROR_HISTORY_SNAPSHOT_RELEASED                                  = 0x2A0B,
  ERROR_RECOVERY_ATTRIBUTES_HAVE_CHANGED                           = 0x2A0C,
  DATA_ENCRYPTION_CAPABILITIES_CHANGED                             = 0x2A0D,
  TIMESTAMP_CHANGED                                                = 0x2A10,
  DATA_ENCRYPTION_PARAMETERS_CHANGED_BY_ANOTHER_I_T_NEXUS          = 0x2A11,
  DATA_ENCRYPTION_PARAMETERS_CHANGED_BY_VENDOR_SPECIFIC_EVENT      = 0x2A12,
  DATA_ENCRYPTION_KEY_INSTANCE_COUNTER_HAS_CHANGED                 = 0x2A13,
  SA_CREATION_CAPABILITIES_DATA_HAS_CHANGED                        = 0x2A14,
  MEDIUM_REMOVAL_PREVENTION_PREEMPTED                              = 0x2A15,
  ZONE_RESET_WRITE_POINTER_RECOMMENDED                             = 0x2A16,
  COPY_CANNOT_EXECUTE_SINCE_HOST_CANNOT_DISCONNECT                 = 0x2B00,
  COMMAND_SEQUENCE_ERROR                                           = 0x2C00,
  TOO_MANY_WINDOWS_SPECIFIED                                       = 0x2C01,
  INVALID_COMBINATION_OF_WINDOWS_SPECIFIED                         = 0x2C02,
  CURRENT_PROGRAM_AREA_IS_NOT_EMPTY                                = 0x2C03,
  CURRENT_PROGRAM_AREA_IS_EMPTY                                    = 0x2C04,
  ILLEGAL_POWER_CONDITION_REQUEST                                  = 0x2C05,
  PERSISTENT_PREVENT_CONFLICT                                      = 0x2C06,
  PREVIOUS_BUSY_STATUS                                             = 0x2C07,
  PREVIOUS_TASK_SET_FULL_STATUS                                    = 0x2C08,
  PREVIOUS_RESERVATION_CONFLICT_STATUS                             = 0x2C09,
  PARTITION_OR_COLLECTION_CONTAINS_USER_OBJECTS                    = 0x2C0A,
  NOT_RESERVED                                                     = 0x2C0B,
  ORWRITE_GENERATION_DOES_NOT_MATCH                                = 0x2C0C,
  RESET_WRITE_POINTER_NOT_ALLOWED                                  = 0x2C0D,
  ZONE_IS_OFFLINE                                                  = 0x2C0E,
  STREAM_NOT_OPEN                                                  = 0x2C0F,
  UNWRITTEN_DATA_IN_ZONE                                           = 0x2C10,
  DESCRIPTOR_FORMAT_SENSE_DATA_REQUIRED                            = 0x2C11,
  OVERWRITE_ERROR_ON_UPDATE_IN_PLACE                               = 0x2D00,
  INSUFFICIENT_TIME_FOR_OPERATION                                  = 0x2E00,
  COMMAND_TIMEOUT_BEFORE_PROCESSING                                = 0x2E01,
  COMMAND_TIMEOUT_DURING_PROCESSING                                = 0x2E02,
  COMMAND_TIMEOUT_DURING_PROCESSING_DUE_TO_ERROR_RECOVERY          = 0x2E03,
  COMMANDS_CLEARED_BY_ANOTHER_INITIATOR                            = 0x2F00,
  COMMANDS_CLEARED_BY_POWER_LOSS_NOTIFICATION                      = 0x2F01,
  COMMANDS_CLEARED_BY_DEVICE_SERVER                                = 0x2F02,
  SOME_COMMANDS_CLEARED_BY_QUEUING_LAYER_EVENT                     = 0x2F03,
  INCOMPATIBLE_MEDIUM_INSTALLED                                    = 0x3000,
  CANNOT_READ_MEDIUM_UNKNOWN_FORMAT                                = 0x3001,
  CANNOT_READ_MEDIUM_INCOMPATIBLE_FORMAT                           = 0x3002,
  CLEANING_CARTRIDGE_INSTALLED                                     = 0x3003,
  CANNOT_WRITE_MEDIUM_UNKNOWN_FORMAT                               = 0x3004,
  CANNOT_WRITE_MEDIUM_INCOMPATIBLE_FORMAT                          = 0x3005,
  CANNOT_FORMAT_MEDIUM_INCOMPATIBLE_MEDIUM                         = 0x3006,
  CLEANING_FAILURE                                                 = 0x3007,
  CANNOT_WRITE_APPLICATION_CODE_MISMATCH                           = 0x3008,
  CURRENT_SESSION_NOT_FIXATED_FOR_APPEND                           = 0x3009,
  CLEANING_REQUEST_REJECTED                                        = 0x300A,
  WORM_MEDIUM_OVERWRITE_ATTEMPTED                                  = 0x300C,
  WORM_MEDIUM_INTEGRITY_CHECK                                      = 0x300D,
  MEDIUM_NOT_FORMATTED                                             = 0x3010,
  INCOMPATIBLE_VOLUME_TYPE                                         = 0x3011,
  INCOMPATIBLE_VOLUME_QUALIFIER                                    = 0x3012,
  CLEANING_VOLUME_EXPIRED                                          = 0x3013,
  MEDIUM_FORMAT_CORRUPTED                                          = 0x3100,
  FORMAT_COMMAND_FAILED                                            = 0x3101,
  ZONED_FORMATTING_FAILED_DUE_TO_SPARE_LINKING                     = 0x3102,
  SANITIZE_COMMAND_FAILED                                          = 0x3103,
  NO_DEFECT_SPARE_LOCATION_AVAILABLE                               = 0x3200,
  DEFECT_LIST_UPDATE_FAILURE                                       = 0x3201,
  TAPE_LENGTH_ERROR                                                = 0x3300,
  ENCLOSURE_FAILURE                                                = 0x3400,
  ENCLOSURE_SERVICES_FAILURE                                       = 0x3500,
  UNSUPPORTED_ENCLOSURE_FUNCTION                                   = 0x3501,
  ENCLOSURE_SERVICES_UNAVAILABLE                                   = 0x3502,
  ENCLOSURE_SERVICES_TRANSFER_FAILURE                              = 0x3503,
  ENCLOSURE_SERVICES_TRANSFER_REFUSED                              = 0x3504,
  ENCLOSURE_SERVICES_CHECKSUM_ERROR                                = 0x3505,
  RIBBON_INK_OR_TONER_FAILURE                                      = 0x3600,
  ROUNDED_PARAMETER                                                = 0x3700,
  EVENT_STATUS_NOTIFICATION                                        = 0x3800,
  ESN_POWER_MANAGEMENT_CLASS_EVENT                                 = 0x3802,
  ESN_MEDIA_CLASS_EVENT                                            = 0x3804,
  ESN_DEVICE_BUSY_CLASS_EVENT                                      = 0x3806,
  THIN_PROVISIONING_SOFT_THRESHOLD_REACHED                         = 0x3807,
  SAVING_PARAMETERS_NOT_SUPPORTED                                  = 0x3900,
  MEDIUM_NOT_PRESENT                                               = 0x3A00,
  MEDIUM_NOT_PRESENT_TRAY_CLOSED                                   = 0x3A01,
  MEDIUM_NOT_PRESENT_TRAY_OPEN                                     = 0x3A02,
  MEDIUM_NOT_PRESENT_LOADABLE                                      = 0x3A03,
  MEDIUM_NOT_PRESENT_MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE            = 0x3A04,
  SEQUENTIAL_POSITIONING_ERROR                                     = 0x3B00,
  TAPE_POSITION_ERROR_AT_BEGINNING_OF_MEDIUM                       = 0x3B01,
  TAPE_POSITION_ERROR_AT_END_OF_MEDIUM                             = 0x3B02,
  TAPE_OR_ELECTRONIC_VERTICAL_FORMS_UNIT_NOT_READY                 = 0x3B03,
  SLEW_FAILURE                                                     = 0x3B04,
  PAPER_JAM                                                        = 0x3B05,
  FAILED_TO_SENSE_TOP_OF_FORM                                      = 0x3B06,
  FAILED_TO_SENSE_BOTTOM_OF_FORM                                   = 0x3B07,
  REPOSITION_ERROR                                                 = 0x3B08,
  READ_PAST_END_OF_MEDIUM                                          = 0x3B09,
  READ_PAST_BEGINNING_OF_MEDIUM                                    = 0x3B0A,
  POSITION_PAST_END_OF_MEDIUM                                      = 0x3B0B,
  POSITION_PAST_BEGINNING_OF_MEDIUM                                = 0x3B0C,
  MEDIUM_DESTINATION_ELEMENT_FULL                                  = 0x3B0D,
  MEDIUM_SOURCE_ELEMENT_EMPTY                                      = 0x3B0E,
  END_OF_MEDIUM_REACHED                                            = 0x3B0F,
  MEDIUM_MAGAZINE_NOT_ACCESSIBLE                                   = 0x3B11,
  MEDIUM_MAGAZINE_REMOVED                                          = 0x3B12,
  MEDIUM_MAGAZINE_INSERTED                                         = 0x3B13,
  MEDIUM_MAGAZINE_LOCKED                                           = 0x3B14,
  MEDIUM_MAGAZINE_UNLOCKED                                         = 0x3B15,
  MECHANICAL_POSITIONING_OR_CHANGER_ERROR                          = 0x3B16,
  READ_PAST_END_OF_USER_OBJECT                                     = 0x3B17,
  ELEMENT_DISABLED                                                 = 0x3B18,
  ELEMENT_ENABLED                                                  = 0x3B19,
  DATA_TRANSFER_DEVICE_REMOVED                                     = 0x3B1A,
  DATA_TRANSFER_DEVICE_INSERTED                                    = 0x3B1B,
  TOO_MANY_LOGICAL_OBJECTS_ON_PARTITION_TO_SUPPORT_OPERATION       = 0x3B1C,
  CUSTOM_3C00                                                      = 0x3C00,
  INVALID_BITS_IN_IDENTIFY_MESSAGE                                 = 0x3D00,
  LOGICAL_UNIT_HAS_NOT_SELF_CONFIGURED_YET                         = 0x3E00,
  LOGICAL_UNIT_FAILURE                                             = 0x3E01,
  TIMEOUT_ON_LOGICAL_UNIT                                          = 0x3E02,
  LOGICAL_UNIT_FAILED_SELF_TEST                                    = 0x3E03,
  LOGICAL_UNIT_UNABLE_TO_UPDATE_SELF_TEST_LOG                      = 0x3E04,
  TARGET_OPERATING_CONDITIONS_HAVE_CHANGED                         = 0x3F00,
  MICROCODE_HAS_BEEN_CHANGED                                       = 0x3F01,
  CHANGED_OPERATING_DEFINITION                                     = 0x3F02,
  INQUIRY_DATA_HAS_CHANGED                                         = 0x3F03,
  COMPONENT_DEVICE_ATTACHED                                        = 0x3F04,
  DEVICE_IDENTIFIER_CHANGED                                        = 0x3F05,
  REDUNDANCY_GROUP_CREATED_OR_MODIFIED                             = 0x3F06,
  REDUNDANCY_GROUP_DELETED                                         = 0x3F07,
  SPARE_CREATED_OR_MODIFIED                                        = 0x3F08,
  SPARE_DELETED                                                    = 0x3F09,
  VOLUME_SET_CREATED_OR_MODIFIED                                   = 0x3F0A,
  VOLUME_SET_DELETED                                               = 0x3F0B,
  VOLUME_SET_DEASSIGNED                                            = 0x3F0C,
  VOLUME_SET_REASSIGNED                                            = 0x3F0D,
  REPORTED_LUNS_DATA_HAS_CHANGED                                   = 0x3F0E,
  ECHO_BUFFER_OVERWRITTEN                                          = 0x3F0F,
  MEDIUM_LOADABLE                                                  = 0x3F10,
  MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE                               = 0x3F11,
  iSCSI_IP_ADDRESS_ADDED                                           = 0x3F12,
  iSCSI_IP_ADDRESS_REMOVED                                         = 0x3F13,
  iSCSI_IP_ADDRESS_CHANGED                                         = 0x3F14,
  INSPECT_REFERRALS_SENSE_DESCRIPTORS                              = 0x3F15,
  MICROCODE_HAS_BEEN_CHANGED_WITHOUT_RESET                         = 0x3F16,
  ZONE_TRANSITION_TO_FULL                                          = 0x3F17,
  BIND_COMPLETED                                                   = 0x3F18,
  BIND_REDIRECTED                                                  = 0x3F19,
  SUBSIDIARY_BINDING_CHANGED                                       = 0x3F1A,
  RAM_FAILURE_SHOULD_USE_40_NN                                     = 0x4000,
  DATA_PATH_FAILURE_SHOULD_USE_40_NN                               = 0x4100,
  POWER_ON_OR_SELF_TEST_FAILURE_SHOULD_USE_40_NN                   = 0x4200,
  MESSAGE_ERROR                                                    = 0x4300,
  INTERNAL_TARGET_FAILURE                                          = 0x4400,
  PERSISTENT_RESERVATION_INFORMATION_LOST                          = 0x4401,
  ATA_DEVICE_FAILED_SET_FEATURES                                   = 0x4471,
  SELECT_OR_RESELECT_FAILURE                                       = 0x4500,
  UNSUCCESSFUL_SOFT_RESET                                          = 0x4600,
  SCSI_PARITY_ERROR                                                = 0x4700,
  DATA_PHASE_CRC_ERROR_DETECTED                                    = 0x4701,
  SCSI_PARITY_ERROR_DETECTED_DURING_ST_DATA_PHASE                  = 0x4702,
  INFORMATION_UNIT_iuCRC_ERROR_DETECTED                            = 0x4703,
  ASYNCHRONOUS_INFORMATION_PROTECTION_ERROR_DETECTED               = 0x4704,
  PROTOCOL_SERVICE_CRC_ERROR                                       = 0x4705,
  PHY_TEST_FUNCTION_IN_PROGRESS                                    = 0x4706,
  SOME_COMMANDS_CLEARED_BY_ISCSI_PROTOCOL_EVENT                    = 0x477F,
  INITIATOR_DETECTED_ERROR_MESSAGE_RECEIVED                        = 0x4800,
  INVALID_MESSAGE_ERROR                                            = 0x4900,
  COMMAND_PHASE_ERROR                                              = 0x4A00,
  DATA_PHASE_ERROR                                                 = 0x4B00,
  INVALID_TARGET_PORT_TRANSFER_TAG_RECEIVED                        = 0x4B01,
  TOO_MUCH_WRITE_DATA                                              = 0x4B02,
  ACK_NAK_TIMEOUT                                                  = 0x4B03,
  NAK_RECEIVED                                                     = 0x4B04,
  DATA_OFFSET_ERROR                                                = 0x4B05,
  INITIATOR_RESPONSE_TIMEOUT                                       = 0x4B06,
  CONNECTION_LOST                                                  = 0x4B07,
  DATA_IN_BUFFER_OVERFLOW_DATA_BUFFER_SIZE                         = 0x4B08,
  DATA_IN_BUFFER_OVERFLOW_DATA_BUFFER_DESCRIPTOR_AREA              = 0x4B09,
  DATA_IN_BUFFER_ERROR                                             = 0x4B0A,
  DATA_OUT_BUFFER_OVERFLOW_DATA_BUFFER_SIZE                        = 0x4B0B,
  DATA_OUT_BUFFER_OVERFLOW_DATA_BUFFER_DESCRIPTOR_AREA             = 0x4B0C,
  DATA_OUT_BUFFER_ERROR                                            = 0x4B0D,
  PCIE_FABRIC_ERROR                                                = 0x4B0E,
  PCIE_COMPLETION_TIMEOUT                                          = 0x4B0F,
  PCIE_COMPLETER_ABORT                                             = 0x4B10,
  PCIE_POISONED_TLP_RECEIVED                                       = 0x4B11,
  PCIE_ECRC_CHECK_FAILED                                           = 0x4B12,
  PCIE_UNSUPPORTED_REQUEST                                         = 0x4B13,
  PCIE_ACS_VIOLATION                                               = 0x4B14,
  PCIE_TLP_PREFIX_BLOCKED                                          = 0x4B15,
  LOGICAL_UNIT_FAILED_SELF_CONFIGURATION                           = 0x4C00,
  OVERLAPPED_COMMANDS_ATTEMPTED                                    = 0x4E00,
  CUSTOM_4F00                                                      = 0x4F00,
  WRITE_APPEND_ERROR                                               = 0x5000,
  WRITE_APPEND_POSITION_ERROR                                      = 0x5001,
  POSITION_ERROR_RELATED_TO_TIMING                                 = 0x5002,
  ERASE_FAILURE                                                    = 0x5100,
  ERASE_FAILURE_INCOMPLETE_ERASE_OPERATION_DETECTED                = 0x5101,
  CARTRIDGE_FAULT                                                  = 0x5200,
  MEDIA_LOAD_OR_EJECT_FAILED                                       = 0x5300,
  UNLOAD_TAPE_FAILURE                                              = 0x5301,
  MEDIUM_REMOVAL_PREVENTED                                         = 0x5302,
  MEDIUM_REMOVAL_PREVENTED_BY_DATA_TRANSFER_ELEMENT                = 0x5303,
  MEDIUM_THREAD_OR_UNTHREAD_FAILURE                                = 0x5304,
  VOLUME_IDENTIFIER_INVALID                                        = 0x5305,
  VOLUME_IDENTIFIER_MISSING                                        = 0x5306,
  DUPLICATE_VOLUME_IDENTIFIER                                      = 0x5307,
  ELEMENT_STATUS_UNKNOWN                                           = 0x5308,
  DATA_TRANSFER_DEVICE_ERROR_LOAD_FAILED                           = 0x5309,
  DATA_TRANSFER_DEVICE_ERROR_UNLOAD_FAILED                         = 0x530A,
  DATA_TRANSFER_DEVICE_ERROR_UNLOAD_MISSING                        = 0x530B,
  DATA_TRANSFER_DEVICE_ERROR_EJECT_FAILED                          = 0x530C,
  DATA_TRANSFER_DEVICE_ERROR_LIBRARY_COMMUNICATION_FAILED          = 0x530D,
  SCSI_TO_HOST_SYSTEM_INTERFACE_FAILURE                            = 0x5400,
  SYSTEM_RESOURCE_FAILURE                                          = 0x5500,
  SYSTEM_BUFFER_FULL                                               = 0x5501,
  INSUFFICIENT_RESERVATION_RESOURCES                               = 0x5502,
  INSUFFICIENT_RESOURCES                                           = 0x5503,
  INSUFFICIENT_REGISTRATION_RESOURCES                              = 0x5504,
  INSUFFICIENT_ACCESS_CONTROL_RESOURCES                            = 0x5505,
  AUXILIARY_MEMORY_OUT_OF_SPACE                                    = 0x5506,
  QUOTA_ERROR                                                      = 0x5507,
  MAXIMUM_NUMBER_OF_SUPPLEMENTAL_DECRYPTION_KEYS_EXCEEDED          = 0x5508,
  MEDIUM_AUXILIARY_MEMORY_NOT_ACCESSIBLE                           = 0x5509,
  DATA_CURRENTLY_UNAVAILABLE                                       = 0x550A,
  INSUFFICIENT_POWER_FOR_OPERATION                                 = 0x550B,
  INSUFFICIENT_RESOURCES_TO_CREATE_ROD                             = 0x550C,
  INSUFFICIENT_RESOURCES_TO_CREATE_ROD_TOKEN                       = 0x550D,
  INSUFFICIENT_ZONE_RESOURCES                                      = 0x550E,
  INSUFFICIENT_ZONE_RESOURCES_TO_COMPLETE_WRITE                    = 0x550F,
  MAXIMUM_NUMBER_OF_STREAMS_OPEN                                   = 0x5510,
  INSUFFICIENT_RESOURCES_TO_BIND                                   = 0x5511,
  CUSTOM_5600                                                      = 0x5600,
  UNABLE_TO_RECOVER_TABLE_OF_CONTENTS                              = 0x5700,
  GENERATION_DOES_NOT_EXIST                                        = 0x5800,
  UPDATED_BLOCK_READ                                               = 0x5900,
  OPERATOR_REQUEST_OR_STATE_CHANGE_INPUT                           = 0x5A00,
  OPERATOR_MEDIUM_REMOVAL_REQUEST                                  = 0x5A01,
  OPERATOR_SELECTED_WRITE_PROTECT                                  = 0x5A02,
  OPERATOR_SELECTED_WRITE_PERMIT                                   = 0x5A03,
  LOG_EXCEPTION                                                    = 0x5B00,
  THRESHOLD_CONDITION_MET                                          = 0x5B01,
  LOG_COUNTER_AT_MAXIMUM                                           = 0x5B02,
  LOG_LIST_CODES_EXHAUSTED                                         = 0x5B03,
  RPL_STATUS_CHANGE                                                = 0x5C00,
  SPINDLES_SYNCHRONIZED                                            = 0x5C01,
  SPINDLES_NOT_SYNCHRONIZED                                        = 0x5C02,
  FAILURE_PREDICTION_THRESHOLD_EXCEEDED                            = 0x5D00,
  MEDIA_FAILURE_PREDICTION_THRESHOLD_EXCEEDED                      = 0x5D01,
  LOGICAL_UNIT_FAILURE_PREDICTION_THRESHOLD_EXCEEDED               = 0x5D02,
  SPARE_AREA_EXHAUSTION_PREDICTION_THRESHOLD_EXCEEDED              = 0x5D03,
  HARDWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE            = 0x5D10,
  HARDWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH             = 0x5D11,
  HARDWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH              = 0x5D12,
  HARDWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH              = 0x5D13,
  HARDWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS              = 0x5D14,
  HARDWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                 = 0x5D15,
  HARDWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH             = 0x5D16,
  HARDWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                   = 0x5D17,
  HARDWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                   = 0x5D18,
  HARDWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                = 0x5D19,
  HARDWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                 = 0x5D1A,
  HARDWARE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                   = 0x5D1B,
  HARDWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT         = 0x5D1C,
  HARDWARE_IMPENDING_FAILURE_POWER_LOSS_PROTECTION_CIRCUIT         = 0x5D1D,
  CONTROLLER_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE          = 0x5D20,
  CONTROLLER_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH           = 0x5D21,
  CONTROLLER_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH            = 0x5D22,
  CONTROLLER_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH            = 0x5D23,
  CONTROLLER_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS            = 0x5D24,
  CONTROLLER_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH               = 0x5D25,
  CONTROLLER_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH           = 0x5D26,
  CONTROLLER_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                 = 0x5D27,
  CONTROLLER_IMPENDING_FAILURE_CONTROLLER_DETECTED                 = 0x5D28,
  CONTROLLER_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE              = 0x5D29,
  CONTROLLER_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE               = 0x5D2A,
  CONTROLLER_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                 = 0x5D2B,
  CONTROLLER_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT       = 0x5D2C,
  DATA_CHANNEL_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE        = 0x5D30,
  DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH         = 0x5D31,
  DATA_CHANNEL_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH          = 0x5D32,
  DATA_CHANNEL_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH          = 0x5D33,
  DATA_CHANNEL_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS          = 0x5D34,
  DATA_CHANNEL_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH             = 0x5D35,
  DATA_CHANNEL_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH         = 0x5D36,
  DATA_CHANNEL_IMPENDING_FAILURE_CHANNEL_PARAMETRICS               = 0x5D37,
  DATA_CHANNEL_IMPENDING_FAILURE_CONTROLLER_DETECTED               = 0x5D38,
  DATA_CHANNEL_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE            = 0x5D39,
  DATA_CHANNEL_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE             = 0x5D3A,
  DATA_CHANNEL_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT               = 0x5D3B,
  DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT     = 0x5D3C,
  SERVO_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE               = 0x5D40,
  SERVO_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                = 0x5D41,
  SERVO_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                 = 0x5D42,
  SERVO_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                 = 0x5D43,
  SERVO_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                 = 0x5D44,
  SERVO_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                    = 0x5D45,
  SERVO_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                = 0x5D46,
  SERVO_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                      = 0x5D47,
  SERVO_IMPENDING_FAILURE_CONTROLLER_DETECTED                      = 0x5D48,
  SERVO_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                   = 0x5D49,
  SERVO_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                    = 0x5D4A,
  SERVO_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                      = 0x5D4B,
  SERVO_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT            = 0x5D4C,
  SPINDLE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE             = 0x5D50,
  SPINDLE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH              = 0x5D51,
  SPINDLE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH               = 0x5D52,
  SPINDLE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH               = 0x5D53,
  SPINDLE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS               = 0x5D54,
  SPINDLE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                  = 0x5D55,
  SPINDLE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH              = 0x5D56,
  SPINDLE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                    = 0x5D57,
  SPINDLE_IMPENDING_FAILURE_CONTROLLER_DETECTED                    = 0x5D58,
  SPINDLE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                 = 0x5D59,
  SPINDLE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                  = 0x5D5A,
  SPINDLE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                    = 0x5D5B,
  SPINDLE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT          = 0x5D5C,
  FIRMWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE            = 0x5D60,
  FIRMWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH             = 0x5D61,
  FIRMWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH              = 0x5D62,
  FIRMWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH              = 0x5D63,
  FIRMWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS              = 0x5D64,
  FIRMWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                 = 0x5D65,
  FIRMWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH             = 0x5D66,
  FIRMWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                   = 0x5D67,
  FIRMWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                   = 0x5D68,
  FIRMWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                = 0x5D69,
  FIRMWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                 = 0x5D6A,
  FIRMWARE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                   = 0x5D6B,
  FIRMWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT         = 0x5D6C,
  MEDIA_IMPENDING_FAILURE_ENDURANCE_LIMIT_MET                      = 0x5D73,
  FAILURE_PREDICTION_THRESHOLD_EXCEEDED_FALSE_                     = 0x5DFF,
  LOW_POWER_CONDITION_ON                                           = 0x5E00,
  IDLE_CONDITION_ACTIVATED_BY_TIMER                                = 0x5E01,
  STANDBY_CONDITION_ACTIVATED_BY_TIMER                             = 0x5E02,
  IDLE_CONDITION_ACTIVATED_BY_COMMAND                              = 0x5E03,
  STANDBY_CONDITION_ACTIVATED_BY_COMMAND                           = 0x5E04,
  IDLE_B_CONDITION_ACTIVATED_BY_TIMER                              = 0x5E05,
  IDLE_B_CONDITION_ACTIVATED_BY_COMMAND                            = 0x5E06,
  IDLE_C_CONDITION_ACTIVATED_BY_TIMER                              = 0x5E07,
  IDLE_C_CONDITION_ACTIVATED_BY_COMMAND                            = 0x5E08,
  STANDBY_Y_CONDITION_ACTIVATED_BY_TIMER                           = 0x5E09,
  STANDBY_Y_CONDITION_ACTIVATED_BY_COMMAND                         = 0x5E0A,
  POWER_STATE_CHANGE_TO_ACTIVE                                     = 0x5E41,
  POWER_STATE_CHANGE_TO_IDLE                                       = 0x5E42,
  POWER_STATE_CHANGE_TO_STANDBY                                    = 0x5E43,
  POWER_STATE_CHANGE_TO_SLEEP                                      = 0x5E45,
  POWER_STATE_CHANGE_TO_DEVICE_CONTROL                             = 0x5E47,
  CUSTOM_5F00                                                      = 0x5F00,
  LAMP_FAILURE                                                     = 0x6000,
  VIDEO_ACQUISITION_ERROR                                          = 0x6100,
  UNABLE_TO_ACQUIRE_VIDEO                                          = 0x6101,
  OUT_OF_FOCUS                                                     = 0x6102,
  SCAN_HEAD_POSITIONING_ERROR                                      = 0x6200,
  END_OF_USER_AREA_ENCOUNTERED_ON_THIS_TRACK                       = 0x6300,
  PACKET_DOES_NOT_FIT_IN_AVAILABLE_SPACE                           = 0x6301,
  ILLEGAL_MODE_FOR_THIS_TRACK                                      = 0x6400,
  INVALID_PACKET_SIZE                                              = 0x6401,
  VOLTAGE_FAULT                                                    = 0x6500,
  AUTOMATIC_DOCUMENT_FEEDER_COVER_UP                               = 0x6600,
  AUTOMATIC_DOCUMENT_FEEDER_LIFT_UP                                = 0x6601,
  DOCUMENT_JAM_IN_AUTOMATIC_DOCUMENT_FEEDER                        = 0x6602,
  DOCUMENT_MISS_FEED_AUTOMATIC_IN_DOCUMENT_FEEDER                  = 0x6603,
  CONFIGURATION_FAILURE                                            = 0x6700,
  CONFIGURATION_OF_INCAPABLE_LOGICAL_UNITS_FAILED                  = 0x6701,
  ADD_LOGICAL_UNIT_FAILED                                          = 0x6702,
  MODIFICATION_OF_LOGICAL_UNIT_FAILED                              = 0x6703,
  EXCHANGE_OF_LOGICAL_UNIT_FAILED                                  = 0x6704,
  REMOVE_OF_LOGICAL_UNIT_FAILED                                    = 0x6705,
  ATTACHMENT_OF_LOGICAL_UNIT_FAILED                                = 0x6706,
  CREATION_OF_LOGICAL_UNIT_FAILED                                  = 0x6707,
  ASSIGN_FAILURE_OCCURRED                                          = 0x6708,
  MULTIPLY_ASSIGNED_LOGICAL_UNIT                                   = 0x6709,
  SET_TARGET_PORT_GROUPS_COMMAND_FAILED                            = 0x670A,
  ATA_DEVICE_FEATURE_NOT_ENABLED                                   = 0x670B,
  COMMAND_REJECTED                                                 = 0x670C,
  EXPLICIT_BIND_NOT_ALLOWED                                        = 0x670D,
  LOGICAL_UNIT_NOT_CONFIGURED                                      = 0x6800,
  SUBSIDIARY_LOGICAL_UNIT_NOT_CONFIGURED                           = 0x6801,
  DATA_LOSS_ON_LOGICAL_UNIT                                        = 0x6900,
  MULTIPLE_LOGICAL_UNIT_FAILURES                                   = 0x6901,
  PARITY_DATA_MISMATCH                                             = 0x6902,
  INFORMATIONAL_REFER_TO_LOG                                       = 0x6A00,
  STATE_CHANGE_HAS_OCCURRED                                        = 0x6B00,
  REDUNDANCY_LEVEL_GOT_BETTER                                      = 0x6B01,
  REDUNDANCY_LEVEL_GOT_WORSE                                       = 0x6B02,
  REBUILD_FAILURE_OCCURRED                                         = 0x6C00,
  RECALCULATE_FAILURE_OCCURRED                                     = 0x6D00,
  COMMAND_TO_LOGICAL_UNIT_FAILED                                   = 0x6E00,
  COPY_PROTECTION_KEY_EXCHANGE_FAILURE_AUTHENTICATION_FAILURE      = 0x6F00,
  COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_PRESENT             = 0x6F01,
  COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_ESTABLISHED         = 0x6F02,
  READ_OF_SCRAMBLED_SECTOR_WITHOUT_AUTHENTICATION                  = 0x6F03,
  MEDIA_REGION_CODE_IS_MISMATCHED_TO_LOGICAL_UNIT_REGION           = 0x6F04,
  DRIVE_REGION_MUST_BE_PERMANENT_REGION_RESET_COUNT_ERROR          = 0x6F05,
  INSUFFICIENT_BLOCK_COUNT_FOR_BINDING_NONCE_RECORDING             = 0x6F06,
  CONFLICT_IN_BINDING_NONCE_RECORDING                              = 0x6F07,
  INSUFFICIENT_PERMISSION                                          = 0x6F08,
  INVALID_DRIVE_HOST_PAIRING_SERVER                                = 0x6F09,
  DRIVE_HOST_PAIRING_SUSPENDED                                     = 0x6F0A,
  DECOMPRESSION_EXCEPTION_LONG_ALGORITHM_ID                        = 0x7100,
  SESSION_FIXATION_ERROR                                           = 0x7200,
  SESSION_FIXATION_ERROR_WRITING_LEAD_IN                           = 0x7201,
  SESSION_FIXATION_ERROR_WRITING_LEAD_OUT                          = 0x7202,
  SESSION_FIXATION_ERROR_INCOMPLETE_TRACK_IN_SESSION               = 0x7203,
  EMPTY_OR_PARTIALLY_WRITTEN_RESERVED_TRACK                        = 0x7204,
  NO_MORE_TRACK_RESERVATIONS_ALLOWED                               = 0x7205,
  RMZ_EXTENSION_IS_NOT_ALLOWED                                     = 0x7206,
  NO_MORE_TEST_ZONE_EXTENSIONS_ARE_ALLOWED                         = 0x7207,
  CD_CONTROL_ERROR                                                 = 0x7300,
  POWER_CALIBRATION_AREA_ALMOST_FULL                               = 0x7301,
  POWER_CALIBRATION_AREA_IS_FULL                                   = 0x7302,
  POWER_CALIBRATION_AREA_ERROR                                     = 0x7303,
  PROGRAM_MEMORY_AREA_UPDATE_FAILURE                               = 0x7304,
  PROGRAM_MEMORY_AREA_IS_FULL                                      = 0x7305,
  RMA_PMA_IS_ALMOST_FULL                                           = 0x7306,
  CURRENT_POWER_CALIBRATION_AREA_ALMOST_FULL                       = 0x7310,
  CURRENT_POWER_CALIBRATION_AREA_IS_FULL                           = 0x7311,
  RDZ_IS_FULL                                                      = 0x7317,
  SECURITY_ERROR                                                   = 0x7400,
  UNABLE_TO_DECRYPT_DATA                                           = 0x7401,
  UNENCRYPTED_DATA_ENCOUNTERED_WHILE_DECRYPTING                    = 0x7402,
  INCORRECT_DATA_ENCRYPTION_KEY                                    = 0x7403,
  CRYPTOGRAPHIC_INTEGRITY_VALIDATION_FAILED                        = 0x7404,
  ERROR_DECRYPTING_DATA                                            = 0x7405,
  UNKNOWN_SIGNATURE_VERIFICATION_KEY                               = 0x7406,
  ENCRYPTION_PARAMETERS_NOT_USEABLE                                = 0x7407,
  DIGITAL_SIGNATURE_VALIDATION_FAILURE                             = 0x7408,
  ENCRYPTION_MODE_MISMATCH_ON_READ                                 = 0x7409,
  ENCRYPTED_BLOCK_NOT_RAW_READ_ENABLED                             = 0x740A,
  INCORRECT_ENCRYPTION_PARAMETERS                                  = 0x740B,
  UNABLE_TO_DECRYPT_PARAMETER_LIST                                 = 0x740C,
  ENCRYPTION_ALGORITHM_DISABLED                                    = 0x740D,
  SA_CREATION_PARAMETER_VALUE_INVALID                              = 0x7410,
  SA_CREATION_PARAMETER_VALUE_REJECTED                             = 0x7411,
  INVALID_SA_USAGE                                                 = 0x7412,
  DATA_ENCRYPTION_CONFIGURATION_PREVENTED                          = 0x7421,
  SA_CREATION_PARAMETER_NOT_SUPPORTED                              = 0x7430,
  AUTHENTICATION_FAILED                                            = 0x7440,
  EXTERNAL_DATA_ENCRYPTION_KEY_MANAGER_ACCESS_ERROR                = 0x7461,
  EXTERNAL_DATA_ENCRYPTION_KEY_MANAGER_ERROR                       = 0x7462,
  EXTERNAL_DATA_ENCRYPTION_KEY_NOT_FOUND                           = 0x7463,
  EXTERNAL_DATA_ENCRYPTION_REQUEST_NOT_AUTHORIZED                  = 0x7464,
  EXTERNAL_DATA_ENCRYPTION_CONTROL_TIMEOUT                         = 0x746E,
  EXTERNAL_DATA_ENCRYPTION_CONTROL_ERROR                           = 0x746F,
  LOGICAL_UNIT_ACCESS_NOT_AUTHORIZED                               = 0x7471,
  SECURITY_CONFLICT_IN_TRANSLATED_DEVICE                           = 0x7479,
  CUSTOM_7500                                                      = 0x7500,
  CUSTOM_7600                                                      = 0x7600,
  CUSTOM_7700                                                      = 0x7700,
  CUSTOM_7800                                                      = 0x7800,
  CUSTOM_7900                                                      = 0x7900,
  CUSTOM_7A00                                                      = 0x7A00,
  CUSTOM_7B00                                                      = 0x7B00,
  CUSTOM_7C00                                                      = 0x7C00,
  CUSTOM_7D00                                                      = 0x7D00,
  CUSTOM_7E00                                                      = 0x7E00,
  CUSTOM_7F00                                                      = 0x7F00
};
std::string toString(const ASCQ& e);

} // namespace scsi
} // namespace sid

#endif // _SID_SCSI_CONSTANTS_HPP_
