LIB_PROJ = sid_block
POST_SUBDIRS = client

SOURCE_FILES = \
	datatypes.cpp \
	device.cpp \
	nvme/datatypes.cpp \
	nvme/device.cpp \
	scsi/constants.cpp \
	scsi/datatypes.cpp \
	scsi/device.cpp \
	scsi/iscsi/datatypes.cpp \
	scsi/iscsi/device.cpp \
	scsi/scsi_disk/datatypes.cpp \
	scsi/scsi_disk/device.cpp

include $(SID_ROOT)/build.mk
