LIB_PROJ = sid_common
POST_SUBDIRS = test

SOURCE_FILES = \
	convert.cpp \
	hash.cpp \
	io_buffer.cpp \
	json.cpp \
	json_schema.cpp \
	regex.cpp \
	util.cpp \
	uuid.cpp

include $(SID_ROOT)/build.mk
